/*
THIS IS A GENERATED BUNDLE FOR OBSIDIAN PLUGIN.
DO NOT EDIT THIS FILE DIRECTLY.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JoplinSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian10 = require("obsidian");

// src/settings/PluginSettings.ts
var DEFAULT_SETTINGS = {
  serverUrl: "",
  email: "",
  password: "",
  syncIntervalSec: 300,
  syncOnStartup: false,
  syncFoldersOnly: false,
  conflictStrategy: "duplicate",
  excludePatterns: [".obsidian/", "_conflicts/", "templates/", ".directory", ".noteforge/"],
  attachmentFolder: "attachments",
  maxAttachmentMB: 100,
  clientId: "",
  logLevel: "info",
  syncLog: [],
  e2eePassword: ""
};

// src/settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var JoplinSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Joplin Server").setHeading();
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc("e.g. https://joplin.example.com (without /api)").addText((t) => t.setPlaceholder("https://joplin.example.com").setValue(this.plugin.settings.serverUrl).onChange(async (v) => {
      this.plugin.settings.serverUrl = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Email").addText((t) => t.setValue(this.plugin.settings.email).onChange(async (v) => {
      this.plugin.settings.email = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Password").setDesc("Warning: stored in plaintext in plugin data.json").addText((t) => {
      t.inputEl.type = "password";
      t.setValue(this.plugin.settings.password).onChange(async (v) => {
        this.plugin.settings.password = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Test connection").addButton((b) => b.setButtonText("Test connection").setCta().onClick(async () => {
      b.setDisabled(true).setButtonText("Testing\u2026");
      try {
        await this.plugin.api.login();
        new import_obsidian.Notice("\u2705 Connection OK");
      } catch (e) {
        new import_obsidian.Notice("\u274C Connection failed: " + e.message, 8e3);
      } finally {
        b.setDisabled(false).setButtonText("Test connection");
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Sync behavior").setHeading();
    new import_obsidian.Setting(containerEl).setName("Auto sync interval").setDesc("Seconds. 0 = manual only (min 60)").addText((t) => t.setValue(String(this.plugin.settings.syncIntervalSec)).onChange(async (v) => {
      const n = parseInt(v);
      if (!isNaN(n) && n >= 0) {
        this.plugin.settings.syncIntervalSec = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Sync on startup").addToggle((t) => t.setValue(this.plugin.settings.syncOnStartup).onChange(async (v) => {
      this.plugin.settings.syncOnStartup = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Conflict strategy").addDropdown((d) => d.addOption("duplicate", "Duplicate").addOption("local-wins", "Local wins").addOption("remote-wins", "Remote wins").setValue(this.plugin.settings.conflictStrategy).onChange(async (v) => {
      this.plugin.settings.conflictStrategy = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Scope").setHeading();
    new import_obsidian.Setting(containerEl).setName("Sync folders only").setDesc("When enabled, only sync folder structure (no note files). Useful for testing.").addToggle((t) => t.setValue(this.plugin.settings.syncFoldersOnly).onChange(async (v) => {
      this.plugin.settings.syncFoldersOnly = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Exclude patterns").setDesc("Comma-separated path prefixes to exclude").addText((t) => t.setValue(this.plugin.settings.excludePatterns.join(", ")).onChange(async (v) => {
      this.plugin.settings.excludePatterns = v.split(",").map((s) => s.trim()).filter(Boolean);
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("End-to-end encryption").setHeading();
    const e2eeStatus = this.plugin.e2ee.hasLoadedKeys ? "Keys loaded (" + this.plugin.e2ee.availableMasterKeys.length + " master key(s))" : "No keys loaded";
    new import_obsidian.Setting(containerEl).setName("Status").setDesc(e2eeStatus);
    new import_obsidian.Setting(containerEl).setName("E2EE password").setDesc("Enter your Joplin E2EE password to decrypt items").addText((t) => {
      t.inputEl.type = "password";
      t.setPlaceholder("E2EE password");
      t.setValue(this.plugin.settings.e2eePassword).onChange(async (v) => {
        this.plugin.settings.e2eePassword = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Load E2EE keys").addButton((b) => b.setButtonText("Load keys").setCta().onClick(async () => {
      b.setDisabled(true).setButtonText("Loading\u2026");
      try {
        const pw = this.plugin.settings.e2eePassword;
        if (!pw) {
          new import_obsidian.Notice("Enter E2EE password first");
          b.setDisabled(false).setButtonText("Load keys");
          return;
        }
        const mks = this.plugin.e2ee.availableMasterKeys;
        if (mks.length === 0) {
          new import_obsidian.Notice("No master key items found. Run a sync cycle first.");
          b.setDisabled(false).setButtonText("Load keys");
          return;
        }
        for (const mkId of mks) {
          await this.plugin.e2ee.loadMasterKey(mkId, pw);
        }
        new import_obsidian.Notice("Loaded " + mks.length + " master key(s)");
      } catch (e) {
        new import_obsidian.Notice("E2EE key load failed: " + e.message, 8e3);
      } finally {
        b.setDisabled(false).setButtonText("Load keys");
        this.display();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Sync history").setHeading();
    const log = this.plugin.settings.syncLog;
    if (log.length === 0) {
      containerEl.createEl("p", { text: "No sync history yet." });
    } else {
      const tbl = containerEl.createEl("table");
      const thead = tbl.createEl("thead");
      const hr = thead.createEl("tr");
      hr.createEl("th", { text: "Time" });
      hr.createEl("th", { text: "Type" });
      hr.createEl("th", { text: "OK" });
      hr.createEl("th", { text: "Fail" });
      const tbody = tbl.createEl("tbody");
      for (const e of log) {
        const tr = tbody.createEl("tr");
        tr.createEl("td", { text: new Date(e.time).toLocaleTimeString() });
        tr.createEl("td", { text: e.type });
        tr.createEl("td", { text: String(e.ok) });
        tr.createEl("td", { text: String(e.fail) });
      }
    }
  }
};

// src/api/JoplinServerApi.ts
var import_obsidian2 = require("obsidian");
var JoplinServerApi = class {
  // re-login every 200 API calls
  constructor(getConfig) {
    this.sessionId = null;
    this.callCount = 0;
    this.REFRESH_INTERVAL = 200;
    this.execJsonLogCount = 0;
    this.getConfig = getConfig;
  }
  async login() {
    const { baseUrl, email, password } = this.getConfig();
    const res = await (0, import_obsidian2.requestUrl)({
      url: this.trimSlash(baseUrl) + "/api/sessions",
      method: "POST",
      contentType: "application/json",
      body: JSON.stringify({ email, password }),
      throw: false
    });
    if (res.status !== 200)
      throw new Error("Login failed (" + res.status + "): " + res.text);
    const body = res.json;
    this.sessionId = body.id;
  }
  async rawRequest(method, path, opts = {}) {
    if (!this.sessionId)
      await this.login();
    this.callCount++;
    if (this.callCount >= this.REFRESH_INTERVAL) {
      this.callCount = 0;
      try {
        await this.login();
      } catch {
      }
    }
    const maxRetries = opts.retries ?? 3;
    for (let attempt = 0; ; attempt++) {
      const headers = {
        "X-API-AUTH": this.sessionId,
        "X-API-MIN-VERSION": "2.6.0"
      };
      if (opts.contentType)
        headers["Content-Type"] = opts.contentType;
      const res = await (0, import_obsidian2.requestUrl)({
        url: this.trimSlash(this.getConfig().baseUrl) + path,
        method,
        headers,
        body: opts.body,
        throw: false
      });
      if (res.status === 401 && attempt === 0) {
        await this.login();
        continue;
      }
      if (res.status >= 500 && attempt < maxRetries) {
        await this.sleep(Math.pow(4, attempt) * 1e3);
        continue;
      }
      return { status: res.status, text: res.text, arrayBuffer: res.arrayBuffer };
    }
  }
  safeJson(text) {
    try {
      return JSON.parse(text);
    } catch {
      return null;
    }
  }
  async exec(method, path, opts = {}) {
    const res = await this.rawRequest(method, path, opts);
    let json = null;
    try {
      json = JSON.parse(res.text);
    } catch {
      if (this.execJsonLogCount < 5) {
        this.execJsonLogCount++;
        console.warn("[joplin-sync] non-json response", method, path, "status=" + res.status, "body=" + res.text.slice(0, 200));
      }
    }
    return { ...res, json };
  }
  itemPath(name, suffix = "") {
    return "/api/items/root:/" + encodeURIComponent(name) + ":" + suffix;
  }
  async getItem(name) {
    const res = await this.rawRequest("GET", this.itemPath(name, "/content"));
    if (res.status === 404)
      return null;
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.text;
  }
  async getItemBinary(name) {
    const res = await this.rawRequest("GET", this.itemPath(name, "/content"));
    if (res.status === 404)
      throw new ApiError(404, "Not found");
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.arrayBuffer;
  }
  async putItem(name, content, force = false) {
    const res = await this.exec("PUT", this.itemPath(name, "/content") + (force ? "?force=1" : ""), {
      body: content,
      contentType: "application/octet-stream"
    });
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    if (!res.json)
      throw new ApiError(res.status, "PUT response not JSON: " + res.text.slice(0, 200));
    return {
      id: res.json.id || "",
      updated_time: res.json.updated_time || Date.now()
    };
  }
  async deleteItem(name) {
    const res = await this.exec("DELETE", this.itemPath(name));
    if (res.status !== 200 && res.status !== 404)
      throw new ApiError(res.status, res.text);
  }
  async listChildren(cursor) {
    const q = cursor ? "?cursor=" + encodeURIComponent(cursor) : "";
    const res = await this.exec("GET", "/api/items/root:/:/children" + q);
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    if (!res.json)
      throw new ApiError(res.status, "listChildren body is not JSON: " + res.text.slice(0, 200));
    return res.json;
  }
  async listChildrenOf(parentId, cursor) {
    const base = parentId ? "/api/items/root:/" + parentId + ":/children" : "/api/items/root:/:/children";
    const q = cursor ? "?cursor=" + encodeURIComponent(cursor) : "";
    const res = await this.exec("GET", base + q);
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    if (!res.json)
      throw new ApiError(res.status, "listChildrenOf body is not JSON: " + res.text.slice(0, 200));
    return res.json;
  }
  async delta(cursor) {
    const q = cursor ? "?cursor=" + encodeURIComponent(cursor) : "";
    const res = await this.exec("GET", "/api/items/root:/:/delta" + q);
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    if (!res.json)
      throw new ApiError(res.status, "delta body is not JSON: " + res.text.slice(0, 200));
    const raw = res.json;
    const items = raw.items || [];
    for (const item of items) {
      if (item.item_name)
        item.name = item.item_name;
      if (item.jop_updated_time)
        item.updated_time = item.jop_updated_time;
      if (item.type !== void 0)
        item.type = Number(item.type);
      if (item.item_type !== void 0)
        item.item_type = Number(item.item_type);
    }
    return { items, has_more: !!raw.has_more, cursor: raw.cursor };
  }
  async acquireLock(type, clientType, clientId) {
    const res = await this.exec("POST", "/api/locks", {
      body: JSON.stringify({ type, clientType, clientId }),
      contentType: "application/json"
    });
    if (res.status === 409)
      throw new LockConflictError(res.text);
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    if (!res.json)
      throw new ApiError(res.status, "acquireLock body is not JSON: " + res.text.slice(0, 200));
    return res.json;
  }
  async releaseLock(type, clientType, clientId) {
    await this.exec("DELETE", "/api/locks/" + type + "_" + clientType + "_" + clientId);
  }
  async listLocks() {
    const res = await this.exec("GET", "/api/locks");
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    if (!res.json)
      throw new ApiError(res.status, "listLocks body is not JSON: " + res.text.slice(0, 200));
    return res.json;
  }
  trimSlash(u) {
    return u.replace(/\/+$/, "");
  }
  sleep(ms) {
    return new Promise((r) => window.setTimeout(r, ms));
  }
};
var ApiError = class extends Error {
  constructor(status, text) {
    super("API error " + status + ": " + text);
    this.status = status;
  }
};
var LockConflictError = class extends Error {
};

// src/mapping/MappingStore.ts
var MappingStore = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.data = { version: 1, deltaCursor: "", rootFolderId: "", entries: [], tombstones: [] };
    this.byId = /* @__PURE__ */ new Map();
    this.byPath = /* @__PURE__ */ new Map();
    this.dirty = false;
  }
  get filePath() {
    return this.plugin.manifest.dir + "/data/mapping.json";
  }
  async load() {
    const adapter = this.plugin.app.vault.adapter;
    if (adapter.exists) {
      if (await adapter.exists(this.filePath)) {
        this.data = JSON.parse(await adapter.read(this.filePath));
      }
    }
    this.rebuildIndexes();
  }
  async flush() {
    if (!this.dirty)
      return;
    const adapter = this.plugin.app.vault.adapter;
    const dir = this.plugin.manifest.dir + "/data";
    if (!await adapter.exists(dir))
      await adapter.mkdir(dir);
    const tmp = this.filePath + ".tmp";
    await adapter.write(tmp, JSON.stringify(this.data));
    if (await adapter.exists(this.filePath))
      await adapter.remove(this.filePath);
    await adapter.rename(tmp, this.filePath);
    this.dirty = false;
  }
  getByPath(path) {
    return this.byPath.get(path);
  }
  getById(id) {
    return this.byId.get(id);
  }
  all() {
    return this.data.entries;
  }
  getDeltaCursor() {
    return this.data.deltaCursor;
  }
  setDeltaCursor(cursor) {
    this.data.deltaCursor = cursor;
    this.dirty = true;
  }
  setRootFolderId(id) {
    this.data.rootFolderId = id;
    this.dirty = true;
  }
  get rootFolderId() {
    return this.data.rootFolderId;
  }
  upsert(entry) {
    const existing = this.byId.get(entry.joplinId);
    if (existing) {
      this.byPath.delete(existing.path);
      Object.assign(existing, entry);
      this.byPath.set(existing.path, existing);
    } else {
      this.data.entries.push(entry);
      this.byId.set(entry.joplinId, entry);
      this.byPath.set(entry.path, entry);
    }
    this.dirty = true;
  }
  remove(joplinId) {
    const e = this.byId.get(joplinId);
    if (!e)
      return;
    this.data.entries = this.data.entries.filter((x) => x.joplinId !== joplinId);
    this.byId.delete(joplinId);
    this.byPath.delete(e.path);
    this.dirty = true;
  }
  get tombstones() {
    return this.data.tombstones;
  }
  addTombstone(joplinId, type) {
    this.data.tombstones.push({ joplinId, type, deletedAt: Date.now() });
    this.dirty = true;
  }
  clearTombstone(joplinId) {
    this.data.tombstones = this.data.tombstones.filter((t) => t.joplinId !== joplinId);
    this.dirty = true;
  }
  renamePrefix(oldPrefix, newPrefix) {
    for (const e of this.data.entries) {
      if (e.path === oldPrefix || e.path.startsWith(oldPrefix)) {
        this.byPath.delete(e.path);
        e.path = newPrefix + e.path.slice(oldPrefix.length);
        this.byPath.set(e.path, e);
      }
    }
    this.dirty = true;
  }
  rebuildIndexes() {
    this.byId.clear();
    this.byPath.clear();
    for (const e of this.data.entries) {
      this.byId.set(e.joplinId, e);
      this.byPath.set(e.path, e);
    }
  }
};

// src/core/SyncEngine.ts
var import_obsidian9 = require("obsidian");

// src/convert/JoplinSerializer.ts
var NOTE_FIELD_ORDER = [
  "id",
  "parent_id",
  "created_time",
  "updated_time",
  "is_conflict",
  "latitude",
  "longitude",
  "altitude",
  "author",
  "source_url",
  "is_todo",
  "todo_due",
  "todo_completed",
  "source",
  "source_application",
  "application_data",
  "order",
  "user_created_time",
  "user_updated_time",
  "encryption_cipher_text",
  "encryption_applied",
  "markup_language",
  "is_shared",
  "share_id",
  "conflict_original_id",
  "master_key_id",
  "user_data",
  "deleted_time",
  "type_"
];
var FOLDER_FIELD_ORDER = [
  "id",
  "created_time",
  "updated_time",
  "user_created_time",
  "user_updated_time",
  "encryption_cipher_text",
  "encryption_applied",
  "parent_id",
  "is_shared",
  "share_id",
  "master_key_id",
  "icon",
  "user_data",
  "deleted_time",
  "type_"
];
var RESOURCE_FIELD_ORDER = [
  "id",
  "mime",
  "filename",
  "created_time",
  "updated_time",
  "user_created_time",
  "user_updated_time",
  "file_extension",
  "encryption_cipher_text",
  "encryption_applied",
  "encryption_blob_encrypted",
  "size",
  "is_shared",
  "share_id",
  "master_key_id",
  "user_data",
  "blob_updated_time",
  "ocr_text",
  "ocr_details",
  "ocr_status",
  "ocr_error",
  "type_"
];
var TIME_FIELDS = /* @__PURE__ */ new Set([
  "created_time",
  "updated_time",
  "user_created_time",
  "user_updated_time"
]);
var DEFAULTS = {
  is_conflict: 0,
  latitude: "0.00000000",
  longitude: "0.00000000",
  altitude: "0.0000",
  author: "",
  source_url: "",
  is_todo: 0,
  todo_due: 0,
  todo_completed: 0,
  source: "obsidian-joplin-sync",
  source_application: "net.obsidian.joplin-server-sync",
  application_data: "",
  order: 0,
  encryption_cipher_text: "",
  encryption_applied: 0,
  markup_language: 1,
  is_shared: 0,
  share_id: "",
  conflict_original_id: "",
  master_key_id: "",
  user_data: "",
  deleted_time: 0,
  icon: ""
};
var JoplinSerializer = class {
  serialize(item) {
    const order = this.fieldOrder(item.type_);
    const lines = [];
    lines.push(item.title ?? "");
    lines.push("");
    if (item.type_ === 1 /* Note */) {
      lines.push(item.body ?? "");
      lines.push("");
    }
    for (const key of order) {
      const rawValue = item[key];
      const value = rawValue ?? DEFAULTS[key] ?? "";
      lines.push(key + ": " + (TIME_FIELDS.has(key) ? this.formatTime(Number(value)) : String(value)));
    }
    return lines.join("\n");
  }
  unserialize(raw) {
    const lines = raw.split("\n");
    const item = {};
    let bodyEndIndex = lines.length;
    for (let i = lines.length - 1; i >= 0; i--) {
      const line = lines[i];
      if (line.trim() === "") {
        bodyEndIndex = i;
        break;
      }
      const sep = line.indexOf(":");
      if (sep < 0)
        continue;
      const key = line.slice(0, sep).trim();
      const value = line.slice(sep + 1).trim();
      item[key] = TIME_FIELDS.has(key) ? this.parseTime(value) : this.coerce(key, value);
    }
    const headerBody = lines.slice(0, bodyEndIndex);
    item.title = headerBody[0] ?? "";
    if (item.type_ === 1 /* Note */) {
      item.body = headerBody.slice(2).join("\n");
    }
    item.type_ = Number(item.type_);
    return item;
  }
  fieldOrder(type) {
    switch (type) {
      case 1 /* Note */:
        return NOTE_FIELD_ORDER;
      case 2 /* Folder */:
        return FOLDER_FIELD_ORDER;
      case 4 /* Resource */:
        return RESOURCE_FIELD_ORDER;
      default:
        return NOTE_FIELD_ORDER;
    }
  }
  formatTime(ms) {
    return new Date(ms || 0).toISOString();
  }
  parseTime(s) {
    return s ? new Date(s).getTime() : 0;
  }
  coerce(key, value) {
    const numeric = /* @__PURE__ */ new Set([
      "type_",
      "is_conflict",
      "is_todo",
      "todo_due",
      "todo_completed",
      "encryption_applied",
      "markup_language",
      "is_shared",
      "order",
      "size",
      "deleted_time",
      "blob_updated_time"
    ]);
    return numeric.has(key) ? Number(value) : value;
  }
};

// src/core/SyncInfo.ts
var SUPPORTED_SYNC_VERSION = 3;
var SyncInfoHandler = class {
  constructor(api) {
    this.api = api;
    this._e2eeEnabled = false;
  }
  get e2eeEnabled() {
    return this._e2eeEnabled;
  }
  async checkOrInit() {
    const raw = await this.api.getItem("info.json");
    if (raw === null) {
      const info2 = { version: SUPPORTED_SYNC_VERSION };
      await this.api.putItem("info.json", JSON.stringify(info2));
      return info2;
    }
    const info = JSON.parse(raw);
    if (info.version > SUPPORTED_SYNC_VERSION) {
      throw new Error("Sync target version " + info.version + " > supported " + SUPPORTED_SYNC_VERSION + ". Please update the plugin.");
    }
    if (info.version < SUPPORTED_SYNC_VERSION) {
      throw new Error("Sync target needs upgrade (v" + info.version + "). Run sync in official Joplin client first.");
    }
    this._e2eeEnabled = info.e2ee?.value === true;
    if (this._e2eeEnabled) {
      console.warn("[joplin-sync] E2EE target detected \u2014 read-only decryption mode");
    }
    return info;
  }
};

// src/mapping/IdGenerator.ts
function createJoplinId() {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

// src/core/ChangeQueue.ts
var ChangeQueue = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.items = /* @__PURE__ */ new Map();
    this.debounceMs = 3e3;
    this.persistTimer = null;
  }
  push(change) {
    const prev = this.items.get(change.oldPath ?? change.path);
    if (change.kind === "rename" && prev) {
      this.items.delete(change.oldPath);
    }
    const merged = this.merge(prev, change);
    if (merged)
      this.items.set(change.path, merged);
    else
      this.items.delete(change.path);
    this.persist();
  }
  drain() {
    const now = Date.now();
    const ready = [];
    for (const [path, c] of this.items) {
      if (now - c.time >= this.debounceMs) {
        ready.push(c);
        this.items.delete(path);
      }
    }
    this.persist();
    return ready.sort((a, b) => Number(b.isFolder) - Number(a.isFolder) || a.time - b.time);
  }
  requeue(changes) {
    for (const c of changes)
      this.items.set(c.path, c);
    this.persist();
  }
  get size() {
    return this.items.size;
  }
  merge(prev, next) {
    if (!prev)
      return next;
    if (prev.kind === "create" && next.kind === "delete")
      return null;
    if (prev.kind === "create" && next.kind === "modify")
      return { ...next, kind: "create" };
    if (next.kind === "rename" && prev.kind === "create")
      return { ...next, kind: "create", oldPath: void 0 };
    return next;
  }
  persist() {
    if (this.persistTimer)
      return;
    this.persistTimer = window.setTimeout(async () => {
      this.persistTimer = null;
      const adapter = this.plugin.app.vault.adapter;
      await adapter.write(
        this.plugin.manifest.dir + "/data/queue.json",
        JSON.stringify([...this.items.values()])
      );
    }, 500);
  }
  async restore() {
    const adapter = this.plugin.app.vault.adapter;
    const p = this.plugin.manifest.dir + "/data/queue.json";
    if (await adapter.exists(p)) {
      for (const c of JSON.parse(await adapter.read(p))) {
        this.items.set(c.path, c);
      }
    }
  }
};

// src/vault/VaultWatcher.ts
var import_obsidian3 = require("obsidian");
var VaultWatcher = class {
  constructor(plugin, queue) {
    this.plugin = plugin;
    this.queue = queue;
    this.suppressed = /* @__PURE__ */ new Set();
  }
  start() {
    const v = this.plugin.app.vault;
    this.plugin.registerEvent(v.on("create", (f) => this.onEvent("create", f)));
    this.plugin.registerEvent(v.on("modify", (f) => this.onEvent("modify", f)));
    this.plugin.registerEvent(v.on("delete", (f) => this.onEvent("delete", f)));
    this.plugin.registerEvent(v.on("rename", (f, oldPath) => this.onRename(f, oldPath)));
  }
  suppress(path) {
    this.suppressed.add(path);
  }
  release(path) {
    window.setTimeout(() => this.suppressed.delete(path), 2e3);
  }
  onEvent(kind, f) {
    if (this.suppressed.has(f.path))
      return;
    if (!this.shouldTrack(f))
      return;
    this.queue.push({ kind, path: f.path, isFolder: f instanceof import_obsidian3.TFolder, time: Date.now() });
  }
  onRename(f, oldPath) {
    if (this.suppressed.has(f.path))
      return;
    if (!this.shouldTrack(f))
      return;
    this.queue.push({ kind: "rename", path: f.path, oldPath, isFolder: f instanceof import_obsidian3.TFolder, time: Date.now() });
  }
  shouldTrack(f) {
    const s = this.plugin.settings;
    if (f.path.startsWith(this.plugin.app.vault.configDir + "/"))
      return false;
    if (f.path.startsWith("_conflicts/"))
      return false;
    if (s.excludePatterns.some((p) => f.path.startsWith(p)))
      return false;
    if (f instanceof import_obsidian3.TFile && f.extension !== "md") {
      return true;
    }
    return true;
  }
};

// src/core/LocalPusher.ts
var import_obsidian5 = require("obsidian");

// src/resource/ResourceManager.ts
var import_obsidian4 = require("obsidian");
var MIME_MAP = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  webp: "image/webp",
  svg: "image/svg+xml",
  pdf: "application/pdf",
  mp3: "audio/mpeg",
  mp4: "video/mp4",
  zip: "application/zip"
};
var ResourceManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.serializer = new JoplinSerializer();
    this.hashToId = /* @__PURE__ */ new Map();
  }
  async uploadResource(file) {
    const data = await this.plugin.app.vault.readBinary(file);
    const hash = await sha256(data);
    const existing = this.plugin.mapping.getByPath(file.path);
    if (existing && existing.localHash === hash)
      return existing.joplinId;
    const dedup = this.hashToId.get(hash);
    if (dedup)
      return dedup;
    const maxSize = this.plugin.settings.maxAttachmentMB * 1024 * 1024 || 100 * 1024 * 1024;
    if (data.byteLength > maxSize)
      throw new Error("Attachment too large: " + file.path);
    const id = existing?.joplinId ?? createJoplinId();
    const now = Date.now();
    const st = file.stat || { ctime: now, mtime: now };
    await this.plugin.api.putItem(".resource/" + id, data);
    const meta = {
      id,
      parent_id: "",
      title: file.name,
      mime: MIME_MAP[file.extension.toLowerCase()] ?? "application/octet-stream",
      // Store the FULL relative path in `filename` so the pull side can
      // recreate the original folder structure (not flatten into one dir).
      filename: file.path,
      file_extension: file.extension,
      size: data.byteLength,
      blob_updated_time: now,
      created_time: st.ctime ?? now,
      updated_time: now,
      user_created_time: st.ctime ?? now,
      user_updated_time: st.mtime ?? now,
      type_: 4 /* Resource */,
      encryption_applied: 0,
      encryption_cipher_text: ""
    };
    const res = await this.plugin.api.putItem(id + ".md", this.serializer.serialize(meta));
    this.plugin.mapping.upsert({
      joplinId: id,
      path: file.path,
      type: 4 /* Resource */,
      localHash: hash,
      remoteUpdatedTime: res.updated_time,
      syncedAt: now
    });
    this.hashToId.set(hash, id);
    return id;
  }
  async downloadResource(meta) {
    const existing = this.plugin.mapping.getById(meta.id);
    if (existing && (meta.blob_updated_time ?? 0) <= existing.remoteUpdatedTime)
      return existing.path;
    const blob = await this.plugin.api.getItemBinary(".resource/" + meta.id);
    if (!blob)
      throw new Error("Resource blob missing: " + meta.id);
    const dir = this.plugin.settings.attachmentFolder || "attachments";
    const relName = meta.filename && meta.filename.includes("/") ? meta.filename : dir + "/" + (meta.filename || meta.id + "." + (meta.file_extension || "bin"));
    let path = (0, import_obsidian4.normalizePath)(relName);
    const clash = this.plugin.mapping.getByPath(path);
    if (clash && clash.joplinId !== meta.id) {
      path = (0, import_obsidian4.normalizePath)(dir + "/" + meta.id.slice(0, 7) + "_" + (meta.filename || meta.id + "." + (meta.file_extension || "bin")));
    }
    const watcher = this.plugin.engine?.watcher;
    const write = async () => {
      const f = this.plugin.app.vault.getAbstractFileByPath(path);
      if (f instanceof import_obsidian4.TFile)
        await this.plugin.app.vault.modifyBinary(f, blob);
      else
        await this.plugin.app.vault.createBinary(path, blob);
    };
    if (watcher?.suppress) {
      watcher.suppress(path);
      try {
        await write();
      } finally {
        watcher.release(path);
      }
    } else {
      await write();
    }
    this.plugin.mapping.upsert({
      joplinId: meta.id,
      path,
      type: 4 /* Resource */,
      localHash: await sha256(blob),
      remoteUpdatedTime: meta.blob_updated_time ?? meta.updated_time,
      syncedAt: Date.now()
    });
    return path;
  }
};

// src/core/LocalPusher.ts
var LocalPusher = class {
  constructor(plugin, queue) {
    this.plugin = plugin;
    this.queue = queue;
    this.serializer = new JoplinSerializer();
    this.resources = new ResourceManager(plugin);
  }
  async pushAll() {
    const changes = this.queue.drain();
    let ok = 0;
    const failed = [];
    for (const change of changes) {
      try {
        await this.pushOne(change);
        ok++;
      } catch (e) {
        console.error("[joplin-sync] push failed: " + change.path, e);
        failed.push(change);
      }
    }
    if (failed.length)
      this.queue.requeue(failed);
    return { ok, fail: failed.length };
  }
  async pushOne(c) {
    switch (c.kind) {
      case "create":
      case "modify":
        return this.upsertItem(c.path);
      case "delete":
        return this.deleteItem(c.path, c.isFolder);
      case "rename":
        return this.renameItem(c.oldPath, c.path, c.isFolder);
    }
  }
  async upsertItem(path) {
    const af = this.plugin.app.vault.getAbstractFileByPath(path);
    if (!af)
      return;
    if (af instanceof import_obsidian5.TFolder) {
      await this.ensureFolderChain(path + "/");
      return;
    }
    if (!(af instanceof import_obsidian5.TFile))
      return;
    if (af.extension !== "md") {
      await this.resources.uploadResource(af);
      return;
    }
    const parentPath = af.parent?.path === "/" ? "" : af.parent.path + "/";
    const parentId = await this.ensureFolderChain(parentPath || "");
    const content = await this.plugin.app.vault.read(af);
    const hash = await sha256(content);
    const existing = this.plugin.mapping.getByPath(path);
    if (existing?.localHash === hash)
      return;
    const id = existing?.joplinId ?? createJoplinId();
    let base = {};
    if (existing) {
      const remote = await this.plugin.api.getItem(id + ".md");
      if (remote)
        base = this.serializer.unserialize(remote);
    }
    const item = {
      ...base,
      id,
      parent_id: parentId,
      title: af.basename,
      body: content,
      created_time: base.created_time ?? af.stat.ctime,
      updated_time: Date.now(),
      user_created_time: base.user_created_time ?? af.stat.ctime,
      user_updated_time: af.stat.mtime,
      type_: 1 /* Note */,
      encryption_applied: 0,
      encryption_cipher_text: "",
      markup_language: 1
    };
    const e2ee = this.plugin.e2ee;
    const mkId = e2ee.firstLoadedKeyId;
    if (mkId && this.plugin.engine.e2eeActive) {
      const serialized = this.serializer.serialize(item);
      const encryptedCt = await e2ee.encryptItem(serialized, mkId);
      const cipherItem = {
        id,
        parent_id: parentId,
        title: "",
        body: "",
        created_time: item.created_time,
        updated_time: item.updated_time,
        user_created_time: item.user_created_time,
        user_updated_time: item.user_updated_time,
        type_: 1 /* Note */,
        encryption_applied: 1,
        encryption_cipher_text: encryptedCt,
        markup_language: 1
      };
      const cipherSerialized = this.serializer.serialize(cipherItem);
      const res2 = await this.plugin.api.putItem(id + ".md", cipherSerialized);
      this.plugin.mapping.upsert({
        joplinId: id,
        path,
        type: 1 /* Note */,
        localHash: hash,
        remoteUpdatedTime: res2.updated_time,
        syncedAt: Date.now()
      });
      return;
    }
    const res = await this.plugin.api.putItem(id + ".md", this.serializer.serialize(item));
    this.plugin.mapping.upsert({
      joplinId: id,
      path,
      type: 1 /* Note */,
      localHash: hash,
      remoteUpdatedTime: res.updated_time,
      syncedAt: Date.now()
    });
  }
  async deleteItem(path, isFolder) {
    const key = isFolder ? path + "/" : path;
    const entry = this.plugin.mapping.getByPath(key);
    if (!entry)
      return;
    await this.plugin.api.deleteItem(entry.joplinId + ".md");
    this.plugin.mapping.remove(entry.joplinId);
  }
  async renameItem(oldPath, newPath, isFolder) {
    const key = isFolder ? oldPath + "/" : oldPath;
    const entry = this.plugin.mapping.getByPath(key);
    if (!entry)
      return this.upsertItem(newPath);
    if (isFolder)
      this.plugin.mapping.renamePrefix(oldPath + "/", newPath + "/");
    else
      this.plugin.mapping.upsert({ ...entry, path: newPath });
    await this.upsertItem(isFolder ? newPath : newPath);
  }
  async ensureFolderChain(folderPath) {
    if (!folderPath || folderPath === "/")
      return this.ensureRootFolderId();
    const existing = this.plugin.mapping.getByPath(folderPath);
    if (existing)
      return existing.joplinId;
    const parts = folderPath.replace(/\/$/, "").split("/");
    const parentPath = parts.slice(0, -1).join("/");
    const parentId = await this.ensureFolderChain(parentPath ? parentPath + "/" : "");
    const id = createJoplinId();
    const now = Date.now();
    const item = {
      id,
      parent_id: parentId,
      title: parts[parts.length - 1],
      created_time: now,
      updated_time: now,
      user_created_time: now,
      user_updated_time: now,
      type_: 2 /* Folder */,
      encryption_applied: 0,
      encryption_cipher_text: ""
    };
    const res = await this.plugin.api.putItem(id + ".md", this.serializer.serialize(item));
    this.plugin.mapping.upsert({
      joplinId: id,
      path: folderPath,
      type: 2 /* Folder */,
      localHash: "",
      remoteUpdatedTime: res.updated_time,
      syncedAt: now
    });
    return id;
  }
  async ensureRootFolderId() {
    return "";
  }
};

// src/core/DeltaPuller.ts
var import_obsidian7 = require("obsidian");

// src/core/ConflictResolver.ts
var import_obsidian6 = require("obsidian");
var ConflictResolver = class {
  constructor(plugin, watcher) {
    this.plugin = plugin;
    this.watcher = watcher;
  }
  async resolve(mapping, remote, localContent, targetPath) {
    switch (this.plugin.settings.conflictStrategy) {
      case "local-wins":
        this.plugin.mapping.upsert({ ...mapping, remoteUpdatedTime: remote.updated_time });
        return;
      case "remote-wins":
        return this.applyRemote(mapping, remote);
      case "duplicate":
      default: {
        const ts = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "");
        const base = mapping.path.replace(/\.md$/, "").split("/").pop();
        const conflictPath = (0, import_obsidian6.normalizePath)("_conflicts/" + base + " (conflict " + ts + ").md");
        if (!this.plugin.app.vault.getAbstractFileByPath("_conflicts")) {
          await this.plugin.app.vault.createFolder("_conflicts").catch(() => {
          });
        }
        this.watcher.suppress(conflictPath);
        await this.plugin.app.vault.create(conflictPath, localContent);
        this.watcher.release(conflictPath);
        await this.applyRemote(mapping, remote);
        new import_obsidian6.Notice("Sync conflict: local copy saved to " + conflictPath);
      }
    }
  }
  async applyRemote(mapping, remote) {
    const f = this.plugin.app.vault.getAbstractFileByPath(mapping.path);
    this.watcher.suppress(mapping.path);
    try {
      if (f instanceof import_obsidian6.TFile)
        await this.plugin.app.vault.modify(f, remote.body ?? "");
      else
        await this.plugin.app.vault.create(mapping.path, remote.body ?? "");
    } finally {
      this.watcher.release(mapping.path);
    }
    this.plugin.mapping.upsert({
      ...mapping,
      localHash: await sha256(remote.body ?? ""),
      remoteUpdatedTime: remote.updated_time,
      syncedAt: Date.now()
    });
  }
};

// src/core/pathUtil.ts
function safeFileName(name) {
  const cleaned = (name || "").replace(/[\/\\]/g, "_").replace(/[\x00-\x1f\x7f]/g, "").trim();
  return cleaned || "Untitled";
}

// src/core/DeltaPuller.ts
var DeltaPuller = class {
  // item_id → full path
  constructor(plugin, watcher) {
    this.plugin = plugin;
    this.watcher = watcher;
    this.serializer = new JoplinSerializer();
    this.rootAncestorCache = /* @__PURE__ */ new Map();
    this.acceptAll = false;
    this.folderPathCache = /* @__PURE__ */ new Map();
    this.conflicts = new ConflictResolver(plugin, watcher);
    this.resources = new ResourceManager(plugin);
  }
  belongsToRoot(item) {
    if (this.acceptAll)
      return true;
    const rootId = this.plugin.mapping.rootFolderId;
    if (!rootId)
      return true;
    const hasFolders = this.plugin.mapping.all().some((e) => e.type === 2);
    if (!hasFolders)
      return true;
    let pid = item.parent_id;
    const visited = /* @__PURE__ */ new Set();
    while (pid && !visited.has(pid)) {
      visited.add(pid);
      if (pid === rootId)
        return true;
      const parentMapping = this.plugin.mapping.getById(pid);
      if (!parentMapping)
        return false;
      pid = parentMapping.joplinId;
      break;
    }
    return false;
  }
  async pullAll() {
    let cursor = this.plugin.mapping.getDeltaCursor();
    const allItems = [];
    let ok = 0;
    let fail = 0;
    while (true) {
      const page = await this.plugin.api.delta(cursor || void 0);
      for (const d of page.items) {
        try {
          const items = await this.collectChange(d);
          allItems.push(...items);
          ok++;
        } catch (e) {
          fail++;
          console.error("[joplin-sync] collect delta failed", d.name, e);
        }
      }
      if (page.cursor)
        cursor = page.cursor;
      if (!page.has_more)
        break;
    }
    const folders = allItems.filter((i) => i.type_ === 2 /* Folder */);
    const notes = allItems.filter((i) => i.type_ === 1 /* Note */);
    const resources = allItems.filter((i) => i.type_ === 4 /* Resource */);
    this.buildFolderPaths(folders);
    for (const f of folders) {
      try {
        await this.applyFolder(f);
      } catch (e) {
        fail++;
        console.error("[joplin-sync] folder apply failed", f.title, e);
      }
    }
    if (!this.plugin.settings.syncFoldersOnly) {
      for (const n of notes) {
        try {
          await this.applyNote(n);
        } catch (e) {
          fail++;
          console.error("[joplin-sync] note apply failed", n.title, e);
        }
      }
    }
    for (const r of resources) {
      try {
        await this.applyResource(r);
      } catch (e) {
        fail++;
        console.error("[joplin-sync] resource apply failed", r.id, e);
      }
    }
    this.plugin.mapping.setDeltaCursor(cursor ?? "");
    return { ok, fail };
  }
  /** Download a delta item and return fully unserialized JoplinItems it contains */
  async collectChange(d) {
    if (d.name.startsWith(".resource/")) {
      if (d.type === 3 /* Delete */) {
        await this.applyDelete(d.name.replace(".resource/", ""));
        return [];
      }
      return [];
    }
    if (!/^[0-9a-f]{32}\.md$/.test(d.name))
      return [];
    const id = d.name.slice(0, 32);
    if (d.type === 3 /* Delete */) {
      await this.applyDelete(id);
      return [];
    }
    const raw = await this.plugin.api.getItem(d.name);
    if (raw === null)
      return [];
    const e2ee = this.plugin.e2ee;
    const probe = this.serializer.unserialize(raw);
    if (probe.type_ === 9) {
      e2ee.feedMasterKey(probe);
      return [];
    }
    const item = this.serializer.unserialize(raw);
    item.updated_time = d.jop_updated_time ?? item.updated_time;
    if (e2ee.isEncrypted(item)) {
      try {
        const decryptedBody = await e2ee.decryptItem(item);
        if (decryptedBody !== null) {
          const decrypted = this.serializer.unserialize(decryptedBody);
          decrypted.updated_time = item.updated_time;
          if (!this.belongsToRoot(decrypted))
            return [];
          return [decrypted];
        }
      } catch (e) {
        console.warn("[joplin-sync] E2EE decrypt failed for " + d.name + ": " + e.message);
        return [];
      }
    }
    if (!this.belongsToRoot(item))
      return [];
    return [item];
  }
  async applyNote(item) {
    const mapping = this.plugin.mapping.getById(item.id);
    const targetDir = this.resolveFolderPath(item.parent_id);
    const targetPath = this.uniquePath(targetDir, this.sanitize(item.title), item.id);
    if (!mapping) {
      await this.writeFile(targetPath, item.body ?? "");
      await this.saveMapping(item, targetPath);
      return;
    }
    if (item.updated_time <= mapping.remoteUpdatedTime)
      return;
    const localFile = this.plugin.app.vault.getAbstractFileByPath(mapping.path);
    const localContent = localFile ? await this.plugin.app.vault.read(localFile) : null;
    const localChanged = localContent !== null && await sha256(localContent) !== mapping.localHash;
    if (localChanged) {
      await this.conflicts.resolve(mapping, item, localContent, targetPath);
      return;
    }
    if (mapping.path !== targetPath && localFile) {
      this.watcher.suppress(mapping.path);
      this.watcher.suppress(targetPath);
      await this.plugin.app.vault.rename(localFile, targetPath);
      this.watcher.release(mapping.path);
      this.watcher.release(targetPath);
    }
    await this.writeFile(targetPath, item.body ?? "");
    await this.saveMapping(item, targetPath);
  }
  async applyFolder(item) {
    const parentPath = this.resolveFolderPath(item.parent_id);
    const path = parentPath + this.sanitize(item.title) + "/";
    const mapping = this.plugin.mapping.getById(item.id);
    const dirPath = path.replace(/\/$/, "");
    if (!this.plugin.app.vault.getAbstractFileByPath(dirPath)) {
      if (parentPath && !this.plugin.app.vault.getAbstractFileByPath(parentPath.replace(/\/$/, ""))) {
        this.watcher.suppress(parentPath.replace(/\/$/, ""));
        try {
          await this.plugin.app.vault.createFolder(parentPath.replace(/\/$/, ""));
        } catch {
        }
        this.watcher.release(parentPath.replace(/\/$/, ""));
      }
      this.watcher.suppress(dirPath);
      await this.plugin.app.vault.createFolder(dirPath).catch(() => {
      });
      this.watcher.release(dirPath);
    }
    if (mapping && mapping.path !== path) {
      const oldDir = mapping.path.replace(/\/$/, "");
      const f = this.plugin.app.vault.getAbstractFileByPath(oldDir);
      if (f) {
        this.watcher.suppress(oldDir);
        this.watcher.suppress(dirPath);
        await this.plugin.app.vault.rename(f, dirPath);
        this.watcher.release(oldDir);
        this.watcher.release(dirPath);
      }
      this.plugin.mapping.renamePrefix(mapping.path, path);
    }
    this.plugin.mapping.upsert({
      joplinId: item.id,
      path,
      type: 2 /* Folder */,
      localHash: "",
      remoteUpdatedTime: item.updated_time,
      syncedAt: Date.now()
    });
  }
  async applyDelete(id) {
    const mapping = this.plugin.mapping.getById(id);
    if (!mapping)
      return;
    const f = this.plugin.app.vault.getAbstractFileByPath(mapping.path.replace(/\/$/, ""));
    if (f) {
      this.watcher.suppress(f.path);
      if (f instanceof import_obsidian7.TFile) {
        this.plugin.app.fileManager.trashFile(f).catch(() => {
        });
      }
      this.watcher.release(f.path);
    }
    this.plugin.mapping.remove(id);
  }
  async writeFile(path, content) {
    this.watcher.suppress(path);
    try {
      const parentDir = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "";
      if (parentDir && !this.plugin.app.vault.getAbstractFileByPath(parentDir)) {
        try {
          await this.plugin.app.vault.createFolder(parentDir);
        } catch {
        }
      }
      const existing = this.plugin.app.vault.getAbstractFileByPath(path);
      if (existing instanceof import_obsidian7.TFile)
        await this.plugin.app.vault.modify(existing, content);
      else
        await this.plugin.app.vault.create(path, content);
    } finally {
      this.watcher.release(path);
    }
  }
  async saveMapping(item, path) {
    this.plugin.mapping.upsert({
      joplinId: item.id,
      path,
      type: 1 /* Note */,
      localHash: await sha256(item.body ?? ""),
      remoteUpdatedTime: item.updated_time,
      syncedAt: Date.now()
    });
  }
  async applyResource(item) {
    try {
      await this.resources.downloadResource(item);
    } catch (e) {
      console.error("[joplin-sync] download resource failed: " + item.id, e);
    }
  }
  resolveFolderPath(parentId) {
    if (!parentId)
      return "";
    const cached = this.folderPathCache.get(parentId);
    if (cached !== void 0)
      return cached;
    const m = this.plugin.mapping.getById(parentId);
    return m ? m.path : "";
  }
  /** Pre-compute folder paths from delta items (no mapping dependency) */
  buildFolderPaths(folders) {
    this.folderPathCache.clear();
    const sanitize = (t) => safeFileName(t);
    const known = /* @__PURE__ */ new Map();
    for (const f of folders)
      known.set(f.id, sanitize(f.title || ""));
    const paths = /* @__PURE__ */ new Map();
    let remaining = [...folders];
    while (remaining.length > 0) {
      const next = [];
      for (const f of remaining) {
        const parentPath = f.parent_id ? paths.get(f.parent_id) : "";
        if (f.parent_id && parentPath === void 0) {
          next.push(f);
          continue;
        }
        paths.set(f.id, (parentPath || "") + sanitize(f.title || "") + "/");
      }
      if (next.length === remaining.length)
        break;
      remaining = next;
    }
    for (const [id, p] of paths)
      this.folderPathCache.set(id, p);
  }
  sanitize(title) {
    return safeFileName(title);
  }
  uniquePath(dir, name, id) {
    let p = dir + name + ".md";
    const existing = this.plugin.app.vault.getAbstractFileByPath(p);
    const mapped = this.plugin.mapping.getByPath(p);
    if (existing && mapped && mapped.joplinId !== id) {
      p = dir + name + " (" + id.slice(0, 7) + ").md";
    }
    return p;
  }
};

// src/core/InitialSync.ts
var import_obsidian8 = require("obsidian");
var InitialSync = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.serializer = new JoplinSerializer();
  }
  async run() {
    const files = this.collectMarkdownFiles();
    if (files.length === 0) {
      new import_obsidian8.Notice("No markdown files to sync");
      return;
    }
    const folderMap = await this.createFolders(files);
    let done = 0;
    let fail = 0;
    if (this.plugin.settings.syncFoldersOnly) {
      new import_obsidian8.Notice("Folders only mode: skipping note upload");
    } else {
      for (const batch of chunk(files, 5)) {
        await Promise.all(batch.map(async (file) => {
          try {
            const dir = file.path.includes("/") ? file.path.slice(0, file.path.lastIndexOf("/")) : "";
            const parentId = folderMap.get(dir) || "";
            await this.uploadNote(file, parentId);
            done++;
          } catch (e) {
            fail++;
            console.error("[joplin-sync] initial upload fail [" + fail + "]:", file.path, e?.message || e);
          }
        }));
        await this.plugin.mapping.flush();
      }
    }
    let cursor;
    while (true) {
      const page = await this.plugin.api.delta(cursor);
      cursor = page.cursor;
      if (!page.has_more)
        break;
    }
    this.plugin.mapping.setDeltaCursor(cursor ?? "");
    await this.plugin.mapping.flush();
    new import_obsidian8.Notice("Initial sync: " + done + " uploaded" + (fail ? ", " + fail + " failed" : ""));
  }
  async createFolders(files) {
    const folderMap = /* @__PURE__ */ new Map();
    folderMap.set("", "");
    const dirs = /* @__PURE__ */ new Set();
    for (const f of files) {
      const d = f.path.includes("/") ? f.path.slice(0, f.path.lastIndexOf("/")) : "";
      if (!d)
        continue;
      const parts = d.split("/");
      let accumulated = "";
      for (let i = 0; i < parts.length; i++) {
        accumulated = accumulated ? accumulated + "/" + parts[i] : parts[i];
        if (!folderMap.has(accumulated)) {
          const existing = this.plugin.mapping.getByPath(accumulated + "/");
          if (existing) {
            folderMap.set(accumulated, existing.joplinId);
            continue;
          }
          dirs.add(accumulated);
        }
      }
    }
    for (const dp of [...dirs].sort((a, b) => a.split("/").length - b.split("/").length)) {
      const parent = dp.includes("/") ? folderMap.get(dp.slice(0, dp.lastIndexOf("/"))) || "" : "";
      const fid = createJoplinId();
      const title = dp.split("/").pop() || dp;
      const item = {
        id: fid,
        parent_id: parent,
        title,
        type_: 2 /* Folder */,
        created_time: Date.now(),
        updated_time: Date.now(),
        user_created_time: Date.now(),
        user_updated_time: Date.now(),
        encryption_applied: 0,
        encryption_cipher_text: ""
      };
      try {
        const st = await this.plugin.api.putItem(fid + ".md", this.serializer.serialize(item), true);
        if (st && st.id) {
          this.plugin.mapping.upsert({
            joplinId: fid,
            path: dp + "/",
            type: 2 /* Folder */,
            localHash: "",
            remoteUpdatedTime: st.updated_time || Date.now(),
            syncedAt: Date.now()
          });
          folderMap.set(dp, fid);
        }
      } catch (e) {
        console.warn("[joplin-sync] folder create skipped:", dp, e?.message || e);
      }
    }
    return folderMap;
  }
  async uploadNote(file, parentId) {
    const content = await this.plugin.app.vault.read(file);
    const hash = await sha256(content);
    const id = createJoplinId();
    const now = Date.now();
    const item = {
      id,
      parent_id: parentId,
      title: file.basename,
      body: content,
      created_time: file.stat.ctime,
      updated_time: now,
      user_created_time: file.stat.ctime,
      user_updated_time: file.stat.mtime,
      type_: 1 /* Note */,
      encryption_applied: 0,
      encryption_cipher_text: "",
      markup_language: 1
    };
    const res = await this.plugin.api.putItem(id + ".md", this.serializer.serialize(item), true);
    this.plugin.mapping.upsert({
      joplinId: id,
      path: file.path,
      type: 1 /* Note */,
      localHash: hash,
      remoteUpdatedTime: res.updated_time || now,
      syncedAt: now
    });
  }
  collectMarkdownFiles() {
    const excludes = this.plugin.settings.excludePatterns;
    return this.plugin.app.vault.getMarkdownFiles().filter((f) => !excludes.some((p) => f.path.startsWith(p)));
  }
};

// src/core/SyncEngine.ts
var SyncEngine = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.serializer = new JoplinSerializer();
    this.running = false;
    this.state = 0 /* Idle */;
    this.timer = null;
    this.e2eeActive = false;
    this.forcePullFolderPaths = /* @__PURE__ */ new Map();
    this.syncInfo = new SyncInfoHandler(plugin.api);
    this.resources = new ResourceManager(plugin);
  }
  // ============ Phase 1: Legacy full upload ============
  async runFullUpload() {
    if (this.running) {
      new import_obsidian9.Notice("Sync already in progress");
      return;
    }
    this.running = true;
    try {
      await this.plugin.api.login();
      await this.syncInfo.checkOrInit();
      this.e2eeActive = this.syncInfo.e2eeEnabled;
      const files = this.collectMarkdownFiles();
      let done = 0, skipped = 0;
      const failed = [];
      for (const batch of chunk(files, 5)) {
        await Promise.all(batch.map(async (file) => {
          try {
            const changed = await this.uploadNote(file, "");
            changed ? done++ : skipped++;
          } catch (e) {
            failed.push(file.path + ": " + e.message);
          }
          this.plugin.statusBar.setProgress(done + skipped, files.length);
        }));
        await this.plugin.mapping.flush();
      }
      new import_obsidian9.Notice("Upload done: " + done + " uploaded, " + skipped + " unchanged, " + failed.length + " failed");
      if (failed.length)
        console.error("[joplin-sync] failures:", failed);
    } finally {
      this.running = false;
      await this.plugin.mapping.flush();
      this.plugin.statusBar.setIdle();
    }
  }
  async uploadNote(file, parentId, force = false) {
    const content = await this.plugin.app.vault.read(file);
    const hash = await sha256(content);
    const existing = this.plugin.mapping.getByPath(file.path);
    if (!force && existing && existing.localHash === hash)
      return false;
    const id = existing?.joplinId ?? createJoplinId();
    const item = {
      id,
      parent_id: parentId,
      title: file.basename,
      body: content,
      created_time: file.stat.ctime,
      updated_time: file.stat.mtime,
      user_created_time: file.stat.ctime,
      user_updated_time: file.stat.mtime,
      type_: 1 /* Note */,
      encryption_applied: 0,
      encryption_cipher_text: "",
      markup_language: 1
    };
    const payload = this.serializer.serialize(item);
    const result = await this.plugin.api.putItem(id + ".md", payload, force);
    try {
      const raw = await this.plugin.api.getItem(id + ".md");
      if (raw) {
        const remote = this.serializer.unserialize(raw);
        const remoteHash = await sha256(remote.body ?? "");
        if (remoteHash !== hash) {
          console.warn("[joplin-sync] verify mismatch for: " + file.path + " (expected " + hash + ", got " + remoteHash + ")");
        }
      }
    } catch (verifyErr) {
      console.warn("[joplin-sync] verify skipped for: " + file.path + " - " + (verifyErr?.message || verifyErr));
    }
    this.plugin.mapping.upsert({
      joplinId: id,
      path: file.path,
      type: 1 /* Note */,
      localHash: hash,
      remoteUpdatedTime: result.updated_time,
      syncedAt: Date.now()
    });
    return true;
  }
  ensureRootFolder() {
    return "";
  }
  collectMarkdownFiles() {
    const excludes = this.plugin.settings.excludePatterns;
    return this.plugin.app.vault.getMarkdownFiles().filter((f) => !excludes.some((p) => f.path.startsWith(p)));
  }
  // ============ Phase 2: Watcher + Scheduler ============
  startWatching() {
    this.queue = new ChangeQueue(this.plugin);
    void this.queue.restore();
    this.watcher = new VaultWatcher(this.plugin, this.queue);
    this.watcher.start();
    this.pusher = new LocalPusher(this.plugin, this.queue);
    this.deltaPuller = new DeltaPuller(this.plugin, this.watcher);
  }
  ensureReady() {
    if (!this.queue) {
      this.queue = new ChangeQueue(this.plugin);
      void this.queue.restore();
    }
    if (!this.watcher) {
      this.watcher = new VaultWatcher(this.plugin, this.queue);
      this.watcher.start();
    }
    if (!this.pusher)
      this.pusher = new LocalPusher(this.plugin, this.queue);
    if (!this.deltaPuller)
      this.deltaPuller = new DeltaPuller(this.plugin, this.watcher);
  }
  startScheduler() {
    const interval = this.plugin.settings.syncIntervalSec;
    if (interval > 0) {
      this.timer = window.setInterval(() => this.syncCycle(), interval * 1e3);
    }
    if (this.plugin.settings.syncOnStartup) {
      window.setTimeout(() => this.syncCycle(), 5e3);
    }
  }
  // ============ Phase 2: Sync Cycle ============
  async syncCycle() {
    if (this.state !== 0 /* Idle */) {
      new import_obsidian9.Notice("Sync already in progress");
      return;
    }
    this.ensureReady();
    try {
      this.state = 1 /* Pushing */;
      this.plugin.statusBar.setSyncing("pushing...");
      await this.plugin.api.login();
      await this.syncInfo.checkOrInit();
      this.e2eeActive = this.syncInfo.e2eeEnabled;
      if (!this.plugin.mapping.getDeltaCursor()) {
        this.plugin.statusBar.setSyncing("initial sync...");
        await new InitialSync(this.plugin).run();
      }
      this.state = 1 /* Pushing */;
      const pushResult = await this.pusher.pushAll();
      this.plugin.statusBar.setProgress(pushResult.ok, Math.max(pushResult.ok, 1), "push");
      this.state = 2 /* Pulling */;
      this.plugin.statusBar.setSyncing("pulling...");
      const pullResult = await this.deltaPuller.pullAll();
      this.plugin.statusBar.setProgress(pullResult.ok, Math.max(pullResult.ok, 1), "pull");
      this.state = 3 /* Resolving */;
      for (const t of [...this.plugin.mapping.tombstones]) {
        await this.plugin.api.deleteItem(t.joplinId + ".md");
        this.plugin.mapping.clearTombstone(t.joplinId);
      }
      const totalMapped = this.plugin.mapping.all().length;
      this.plugin.statusBar.setOk(Date.now(), totalMapped);
      const totalFail = (pushResult?.fail ?? 0) + (pullResult?.fail ?? 0);
      this.plugin.logSync("sync", totalMapped, totalFail);
      new import_obsidian9.Notice("Sync complete: " + totalMapped + " items mapped, " + totalFail + " failed");
    } catch (e) {
      this.state = 4 /* Error */;
      const msg = e?.message || e?.toString() || "Unknown error";
      console.error("[joplin-sync] sync cycle failed:", msg);
      this.plugin.statusBar.setError(msg);
      new import_obsidian9.Notice("Sync failed: " + msg, 8e3);
    } finally {
      await this.plugin.mapping.flush();
      this.state = 0 /* Idle */;
    }
  }
  async shutdown() {
    if (this.timer)
      window.clearInterval(this.timer);
  }
  // Phase 3: pre-assign note ID for link resolution
  async preassignNoteId(file) {
    const id = createJoplinId();
    this.plugin.mapping.upsert({
      joplinId: id,
      path: file.path,
      type: 1 /* Note */,
      localHash: "",
      remoteUpdatedTime: 0,
      syncedAt: Date.now()
    });
    return id;
  }
  // ============ Force Push: overwrite server with local ============
  async forcePush() {
    if (this.running) {
      new import_obsidian9.Notice("Sync already in progress");
      return;
    }
    this.running = true;
    try {
      this.plugin.statusBar.setSyncing("force push: rebuilding server...");
      await this.plugin.api.login();
      await this.syncInfo.checkOrInit();
      this.e2eeActive = this.syncInfo.e2eeEnabled;
      const rootFolderId = "";
      const files = this.collectMarkdownFiles();
      const pushedNoteIds = /* @__PURE__ */ new Set();
      const pushedFolderIds = /* @__PURE__ */ new Set();
      const folderMap = /* @__PURE__ */ new Map();
      folderMap.set("", rootFolderId);
      const dirs = /* @__PURE__ */ new Set();
      for (const f of files) {
        const d = f.path.includes("/") ? f.path.slice(0, f.path.lastIndexOf("/")) : "";
        if (!d)
          continue;
        const parts = d.split("/");
        let accumulated = "";
        for (let i = 0; i < parts.length; i++) {
          accumulated = accumulated ? accumulated + "/" + parts[i] : parts[i];
          if (!folderMap.has(accumulated)) {
            const existing = this.plugin.mapping.getByPath(accumulated + "/");
            if (existing) {
              folderMap.set(accumulated, existing.joplinId);
              continue;
            }
            dirs.add(accumulated);
          }
        }
      }
      let folderCount = 0;
      for (const dp of [...dirs].sort((a, b) => a.split("/").length - b.split("/").length)) {
        const parent = dp.includes("/") ? folderMap.get(dp.slice(0, dp.lastIndexOf("/"))) || rootFolderId : rootFolderId;
        const fid = createJoplinId();
        const title = dp.split("/").pop() || dp;
        const item = {
          id: fid,
          parent_id: parent,
          title,
          type_: 2 /* Folder */,
          created_time: Date.now(),
          updated_time: Date.now(),
          user_created_time: Date.now(),
          user_updated_time: Date.now(),
          encryption_applied: 0,
          encryption_cipher_text: ""
        };
        try {
          const st = await this.plugin.api.putItem(fid + ".md", this.serializer.serialize(item), true);
          if (st && st.id) {
            this.plugin.mapping.upsert({
              joplinId: fid,
              path: dp + "/",
              type: 2 /* Folder */,
              localHash: "",
              remoteUpdatedTime: st.updated_time || Date.now(),
              syncedAt: Date.now()
            });
            folderMap.set(dp, fid);
            pushedFolderIds.add(fid);
            folderCount++;
          }
        } catch (e) {
        }
      }
      const totalFolders = folderMap.size - 1;
      let done = 0;
      let fail = 0;
      if (this.plugin.settings.syncFoldersOnly) {
        new import_obsidian9.Notice("Force push: " + totalFolders + " folders synced (folders-only mode)");
        this.plugin.logSync("folders", totalFolders, 0);
        done = totalFolders;
      } else {
        for (const batch of chunk(files, 5)) {
          await Promise.all(batch.map(async (file) => {
            try {
              const dir = file.path.includes("/") ? file.path.slice(0, file.path.lastIndexOf("/")) : "";
              const parentId = folderMap.get(dir) || rootFolderId;
              await this.uploadNote(file, parentId, true);
              const m = this.plugin.mapping.getByPath(file.path);
              if (m)
                pushedNoteIds.add(m.joplinId);
              done++;
            } catch (e) {
              fail++;
              console.error("[joplin-sync] upload fail [" + fail + "]:", file.path, e?.message || e);
            }
          }));
          await this.plugin.mapping.flush();
        }
      }
      if (!this.plugin.settings.syncFoldersOnly) {
        console.log("[joplin-sync] force push notes: done=" + done + " fail=" + fail + " pushedNoteIds=" + pushedNoteIds.size);
        this.plugin.logSync("push", done, fail);
      }
      const pushedResourceIds = /* @__PURE__ */ new Set();
      if (!this.plugin.settings.syncFoldersOnly) {
        const excludes = this.plugin.settings.excludePatterns;
        const isExcluded = (p) => excludes.some((e) => p.startsWith(e)) || p.includes("/.obsidian/") || p.startsWith(".obsidian/");
        const allFiles = this.plugin.app.vault.getFiles();
        let rDone = 0, rFail = 0;
        for (const f of allFiles) {
          if (f.extension === "md")
            continue;
          if (isExcluded(f.path))
            continue;
          try {
            const rid = await this.resources.uploadResource(f);
            pushedResourceIds.add(rid);
            rDone++;
          } catch (e) {
            rFail++;
            console.error("[joplin-sync] resource upload fail:", f.path, e?.message || e);
          }
        }
        if (rDone || rFail)
          console.log("[joplin-sync] force push files: " + rDone + " uploaded, " + rFail + " failed");
      }
      let removed = 0, removedNotes = 0, removedFolders = 0, removedResources = 0;
      const remote = await this.listAllRemoteItems();
      console.log("[joplin-sync] force push cleanup: scanning " + remote.length + " remote items");
      for (const stat of remote) {
        const noteMatch = stat.name.match(/^([0-9a-f]{32})\.md$/);
        if (noteMatch) {
          const id = noteMatch[1];
          const entry = this.plugin.mapping.getById(id);
          if (entry?.type === 2 /* Folder */) {
            if (!pushedFolderIds.has(id)) {
              try {
                await this.plugin.api.deleteItem(stat.name);
                removed++;
                removedFolders++;
              } catch {
              }
            }
          } else if (entry?.type === 4 /* Resource */) {
            if (!pushedResourceIds.has(id)) {
              try {
                await this.plugin.api.deleteItem(stat.name);
                removed++;
                removedResources++;
              } catch {
              }
            }
          } else if (!this.plugin.settings.syncFoldersOnly) {
            if (!pushedNoteIds.has(id)) {
              try {
                await this.plugin.api.deleteItem(stat.name);
                removed++;
                removedNotes++;
              } catch {
              }
            }
          }
        } else {
          const resMatch = stat.name.match(/^\.resource\/([0-9a-f]{32})$/);
          if (resMatch && !this.plugin.settings.syncFoldersOnly) {
            const id = resMatch[1];
            if (!pushedResourceIds.has(id)) {
              try {
                await this.plugin.api.deleteItem(stat.name);
                removed++;
              } catch {
              }
            }
          }
        }
      }
      if (removed)
        console.log("[joplin-sync] force push cleaned " + removed + " items (notes=" + removedNotes + " folders=" + removedFolders + " resources=" + removedResources + ")");
      let cursor;
      while (true) {
        const page = await this.plugin.api.delta(cursor);
        cursor = page.cursor;
        if (!page.has_more)
          break;
      }
      this.plugin.mapping.setDeltaCursor(cursor ?? "");
      this.plugin.statusBar.setOk(Date.now(), done);
    } finally {
      this.running = false;
      await this.plugin.mapping.flush();
      this.plugin.statusBar.setIdle();
    }
  }
  // ============ Force Pull: overwrite local with server ============
  async forcePull() {
    if (this.running) {
      new import_obsidian9.Notice("Sync already in progress");
      return;
    }
    this.running = true;
    try {
      this.plugin.statusBar.setSyncing("force pull: clearing local...");
      await this.plugin.api.login();
      const allFiles = this.plugin.app.vault.getFiles();
      let delCount = 0;
      for (const f of allFiles) {
        if (f.extension === "md") {
          this.plugin.app.fileManager.trashFile(f).catch(() => {
          });
          delCount++;
        }
      }
      this.plugin.mapping.setDeltaCursor("");
      console.debug("[joplin-sync] force pull: deleted " + delCount + " local files");
      const remoteStats = await this.listAllRemoteItems();
      const e2ee = this.plugin.e2ee;
      let done = 0;
      let failed = 0;
      let skipped = 0;
      const allItems = [];
      for (const stat of remoteStats) {
        if (!/^[0-9a-f]{32}\.md$/.test(stat.name))
          continue;
        if (stat.name.startsWith(".resource/"))
          continue;
        try {
          const raw = await this.plugin.api.getItem(stat.name);
          if (!raw)
            continue;
          const item = this.serializer.unserialize(raw);
          if (item.type_ === 9) {
            e2ee.feedMasterKey(item);
            continue;
          }
          if (e2ee.isEncrypted(item)) {
            try {
              const ds = await e2ee.decryptItem(item);
              if (ds) {
                const d = this.serializer.unserialize(ds);
                allItems.push(d);
              }
            } catch {
              failed++;
              continue;
            }
          } else {
            allItems.push(item);
          }
        } catch (e) {
          failed++;
          if (failed <= 3)
            console.error("[joplin-sync] force-pull:", stat.name, e);
        }
      }
      const folders = allItems.filter((i) => i.type_ === 2 /* Folder */);
      this.buildForcePullFolderPaths(folders);
      for (const f of folders) {
        if (!f.title) {
          skipped++;
          continue;
        }
        try {
          const parentPath = this.resolveForcePullFolderPath(f.parent_id);
          const dirName = safeFileName(f.title);
          const dirPath = parentPath + dirName;
          if (!this.plugin.app.vault.getAbstractFileByPath(dirPath)) {
            await this.plugin.app.vault.createFolder(dirPath).catch(() => {
            });
          }
          this.plugin.mapping.upsert({
            joplinId: f.id,
            path: dirPath + "/",
            type: 2 /* Folder */,
            localHash: "",
            remoteUpdatedTime: f.updated_time,
            syncedAt: Date.now()
          });
        } catch (e) {
          console.warn("[joplin-sync] force-pull folder:", f.title, e?.message || e);
        }
      }
      const notes = allItems.filter((i) => i.type_ === 1 /* Note */);
      for (const item of notes) {
        if (!item.title) {
          skipped++;
          continue;
        }
        try {
          const dir = this.resolveForcePullFolderPath(item.parent_id);
          const sanitized = safeFileName(item.title);
          const path = dir + sanitized + ".md";
          let body = item.body ?? "";
          if (e2ee.isEncrypted(item)) {
            try {
              const ds = await e2ee.decryptItem(item);
              if (ds) {
                const d = this.serializer.unserialize(ds);
                body = d.body ?? "";
              }
            } catch {
              failed++;
              continue;
            }
          }
          if (dir && !this.plugin.app.vault.getAbstractFileByPath(dir.replace(/\/$/, ""))) {
            try {
              await this.plugin.app.vault.createFolder(dir.replace(/\/$/, ""));
            } catch {
            }
          }
          const existing = this.plugin.app.vault.getAbstractFileByPath(path);
          if (existing) {
            await this.plugin.app.vault.modify(existing, body || "");
          } else {
            await this.plugin.app.vault.create(path, body || "");
          }
          const hash = await sha256(body);
          this.plugin.mapping.upsert({
            joplinId: item.id,
            path,
            type: 1 /* Note */,
            localHash: hash,
            remoteUpdatedTime: item.updated_time,
            syncedAt: Date.now()
          });
          done++;
        } catch (e) {
          failed++;
          const msg = e?.message || "";
          if (msg.includes("401"))
            try {
              await this.plugin.api.login();
            } catch {
            }
          if (failed <= 3)
            console.error("[joplin-sync] force-pull:", item.title, msg);
        }
        this.plugin.statusBar.setProgress(done + failed + skipped, remoteStats.length, "pull");
      }
      let cursor;
      while (true) {
        const page = await this.plugin.api.delta(cursor);
        cursor = page.cursor;
        if (!page.has_more)
          break;
      }
      this.plugin.mapping.setDeltaCursor(cursor ?? "");
      await this.plugin.mapping.flush();
      const resources = allItems.filter((i) => i.type_ === 4 /* Resource */);
      const downloadedPaths = /* @__PURE__ */ new Set();
      let rDone = 0, rFail = 0;
      for (const r of resources) {
        try {
          const p = await this.resources.downloadResource(r);
          if (p)
            downloadedPaths.add(p);
          rDone++;
        } catch (e) {
          rFail++;
          if (rFail <= 3)
            console.error("[joplin-sync] force-pull resource:", r.id, e?.message || e);
        }
      }
      if (rDone || rFail)
        console.log("[joplin-sync] force pull attachments: " + rDone + " downloaded, " + rFail + " failed");
      const excludes = this.plugin.settings.excludePatterns;
      const isExcluded = (p) => excludes.some((e) => p.startsWith(e)) || p.includes("/.obsidian/") || p.startsWith(".obsidian/");
      let localRemoved = 0;
      for (const f of this.plugin.app.vault.getFiles()) {
        if (f.extension === "md")
          continue;
        if (isExcluded(f.path))
          continue;
        if (downloadedPaths.has(f.path))
          continue;
        try {
          await this.plugin.app.fileManager.trashFile(f);
          localRemoved++;
        } catch {
        }
      }
      if (localRemoved)
        console.log("[joplin-sync] force pull removed " + localRemoved + " stale local files");
      new import_obsidian9.Notice("Force pull: " + done + " notes, " + failed + " failed" + (rDone ? ", " + rDone + " attachments" : ""));
      this.plugin.logSync("pull", done, failed);
      this.plugin.statusBar.setOk(Date.now(), done);
    } catch (e) {
      const msg = e?.message || e?.toString() || "Unknown error";
      console.error("[joplin-sync] force pull failed:", msg);
      this.plugin.statusBar.setError(msg);
      new import_obsidian9.Notice("Force pull failed: " + msg, 8e3);
    } finally {
      this.running = false;
      await this.plugin.mapping.flush();
      this.plugin.statusBar.setIdle();
    }
  }
  buildForcePullFolderPaths(folders) {
    this.forcePullFolderPaths.clear();
    const sanitize = (t) => safeFileName(t);
    const paths = /* @__PURE__ */ new Map();
    let remaining = [...folders];
    while (remaining.length > 0) {
      const next = [];
      for (const f of remaining) {
        let parentPath;
        if (f.parent_id) {
          parentPath = paths.get(f.parent_id) ?? this.forcePullFolderPaths.get(f.parent_id);
          if (parentPath === void 0) {
            const m = this.plugin.mapping.getById(f.parent_id);
            if (m) {
              paths.set(f.id, m.path);
              continue;
            }
            next.push(f);
            continue;
          }
        } else {
          parentPath = "";
        }
        paths.set(f.id, parentPath + sanitize(f.title || "") + "/");
      }
      if (next.length === remaining.length)
        break;
      remaining = next;
    }
    for (const [id, p] of paths)
      this.forcePullFolderPaths.set(id, p);
  }
  resolveForcePullFolderPath(parentId) {
    if (!parentId)
      return "";
    const cached = this.forcePullFolderPaths.get(parentId);
    if (cached !== void 0)
      return cached;
    const m = this.plugin.mapping.getById(parentId);
    return m ? m.path : "";
  }
  // Enumerate EVERY live item on the server (notes, folders, resource metadata,
  // and resource blobs). Our addressing is FLAT: every Joplin item lives at
  // `root:/<id>.md` (or `root:/.resource/<id>` for resource blobs), with the
  // logical hierarchy encoded in each item's `parent_id` field — NOT in the
  // file-system path. Because of that, the server's path-based listing exposes
  // ALL items as direct children of root, regardless of their real folder
  // nesting. So we simply paginate `listChildrenOf(root)` to obtain the full
  // live set.
  //
  // Why not the `delta` endpoint? The real Joplin Server's delta feed (a) does
  // NOT return `item_type`, and (b) is a change-log that accumulates delete
  // events forever. Reconstructing "what is currently live" from it is fragile
  // and, in practice, caused forcePush's cleanup to delete every note and
  // forcePull to silently skip the whole vault.
  async listAllRemoteItems() {
    const out = [];
    let cursor;
    while (true) {
      const page = await this.plugin.api.listChildrenOf("", cursor);
      for (const it of page.items) {
        const name = it.name || "";
        if (!name)
          continue;
        out.push({ name, updated_time: Number(it.updated_time) || 0 });
      }
      cursor = page.cursor;
      if (!page.has_more)
        break;
    }
    return out;
  }
};
async function sha256(text) {
  const data = typeof text === "string" ? new TextEncoder().encode(text.replace(/\r\n/g, "\n").replace(/\r/g, "\n")) : text;
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0")).join("");
}
function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size)
    out.push(arr.slice(i, i + size));
  return out;
}

// src/ui/StatusBar.ts
var StatusBar = class {
  constructor(el) {
    this.el = el;
    this.el.addClass("joplin-sync-status");
    this.setIdle();
  }
  setIdle() {
    this.el.setText("");
    this.el.className = "joplin-sync-status";
  }
  setSyncing(phase) {
    const label = phase ? "Joplin: " + phase : "Joplin: syncing\u2026";
    this.el.setText(label);
    this.el.className = "joplin-sync-status syncing";
  }
  setOk(time, count) {
    const t = new Date(time).toLocaleTimeString();
    const suffix = count !== void 0 ? " (" + count + " items)" : "";
    this.el.setText("Joplin: OK " + t + suffix);
    this.el.className = "joplin-sync-status ok";
  }
  setError(msg) {
    this.el.setText("Joplin: error");
    this.el.className = "joplin-sync-status error";
    console.error("[joplin-sync]", msg);
  }
  setProgress(done, total, phase) {
    const prefix = phase ? phase + " " : "";
    this.el.setText("Joplin: " + prefix + done + "/" + total);
  }
};

// src/e2ee/EncryptionService.ts
var GCM_TAG_BITS = 128;
var NONCE_BYTES = 12;
var PBKDF2_ITERATIONS = 1e5;
var KEY_BITS = 256;
var EncryptionService = class {
  constructor() {
    this.loadedKeys = /* @__PURE__ */ new Map();
    this.masterKeyItems = /* @__PURE__ */ new Map();
  }
  /** Feed a MasterKey item (type_=9) to the service so it can be used for decryption */
  feedMasterKey(item) {
    if (item.type_ !== 9)
      return;
    this.masterKeyItems.set(item.id, {
      id: item.id,
      encryptionMethod: item.encryption_method || 7,
      checksum: item.checksum || "",
      encryptedContent: item.encryption_cipher_text || ""
    });
  }
  /** Try decrypting item body using loaded master keys. Returns null if cannot decrypt. */
  async tryDecrypt(item) {
    if (!this.isEncrypted(item))
      return item.body ?? "";
    const plain = await this.decryptItem(item);
    return plain;
  }
  isEncrypted(item) {
    return item.encryption_applied === 1;
  }
  /** Decrypt item: parse header, decrypt chunks with master key */
  async decryptItem(item) {
    if (!this.isEncrypted(item))
      return item.body ?? "";
    const header = this.parseHeader(item.encryption_cipher_text);
    const mk = this.masterKeyItems.get(header.masterKeyId);
    if (!mk)
      throw new Error("Master key not found: " + header.masterKeyId);
    const key = this.loadedKeys.get(header.masterKeyId);
    if (!key)
      throw new Error("Master key not loaded: " + header.masterKeyId + " \u2014 enter password in settings");
    const parts = [];
    for (const chunk2 of header.chunks) {
      const decrypted = await this.decryptChunk(header.method, key, chunk2);
      parts.push(decrypted);
    }
    return parts.join("");
  }
  /** Load master key from encrypted master key item + user password */
  async loadMasterKey(masterKeyId, password) {
    const mk = this.masterKeyItems.get(masterKeyId);
    if (!mk)
      throw new Error("Master key item not found: " + masterKeyId);
    if (!password)
      throw new Error("Password required");
    let payload;
    try {
      payload = JSON.parse(mk.encryptedContent);
    } catch {
      payload = { ct: mk.encryptedContent };
    }
    const salt = this.hexToBytes(payload.salt || "");
    const iv = this.hexToBytes(payload.iv || "");
    const ct = this.hexToBytes(payload.ct || payload.cipherText || "");
    const pbkdf2Key = await crypto.subtle.importKey(
      "raw",
      this.buf(new TextEncoder().encode(password)),
      { name: "PBKDF2" },
      false,
      ["deriveKey"]
    );
    const key = await crypto.subtle.deriveKey(
      { name: "PBKDF2", salt: this.buf(salt), iterations: PBKDF2_ITERATIONS, hash: "SHA-256" },
      pbkdf2Key,
      { name: "AES-GCM", length: KEY_BITS },
      false,
      ["decrypt"]
    );
    const plain = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: this.buf(iv), tagLength: GCM_TAG_BITS },
      key,
      this.buf(this.concat(iv, ct))
    );
    const plainStr = new TextDecoder().decode(plain);
    let mkPayload;
    try {
      mkPayload = JSON.parse(plainStr);
    } catch {
      const rawKey = this.base64ToBytes(plainStr);
      const aesKey = await crypto.subtle.importKey(
        "raw",
        this.buf(rawKey),
        { name: "AES-GCM" },
        false,
        ["decrypt"]
      );
      this.loadedKeys.set(masterKeyId, aesKey);
      return;
    }
    if (mkPayload.encryption_method === 9 /* StringV1 */ || mkPayload.encryption_method === 8 /* FileV1 */) {
      const rawKey = this.hexToBytes(mkPayload.content || "");
      const aesKey = await crypto.subtle.importKey(
        "raw",
        this.buf(rawKey),
        { name: "AES-GCM" },
        false,
        ["decrypt"]
      );
      this.loadedKeys.set(masterKeyId, aesKey);
    } else {
      const rawKey = this.hexToBytes(mkPayload.content || mkPayload.ct || "");
      const aesKey = await crypto.subtle.importKey(
        "raw",
        this.buf(rawKey),
        { name: "AES-GCM" },
        false,
        ["decrypt"]
      );
      this.loadedKeys.set(masterKeyId, aesKey);
    }
  }
  // === Internal: header parsing ===
  parseHeader(ct) {
    let pos = 0;
    const headerLenHex = ct.slice(pos, pos + 6);
    const headerLen = parseInt(headerLenHex, 16);
    pos += 6;
    if (isNaN(headerLen))
      throw new Error("Invalid header length");
    const headerHex = ct.slice(pos, pos + headerLen * 2);
    pos += headerLen * 2;
    const headerBytes = this.hexToBytes(headerHex);
    let hp = 0;
    const version = headerBytes[hp++];
    const method = headerBytes[hp] << 8 | headerBytes[hp + 1];
    hp += 2;
    const masterKeyId = this.bytesToHex(headerBytes.slice(hp, hp + 32));
    hp += 32;
    const chunks = [];
    while (pos < ct.length) {
      const chunkLenHex = ct.slice(pos, pos + 6);
      if (chunkLenHex.length < 6)
        break;
      const chunkLen = parseInt(chunkLenHex, 16);
      pos += 6;
      if (isNaN(chunkLen) || chunkLen <= 0)
        break;
      const chunkHex = ct.slice(pos, pos + chunkLen * 2);
      pos += chunkLen * 2;
      chunks.push(chunkHex);
    }
    return { version, method, masterKeyId, chunks };
  }
  /** Decrypt a single hex-encoded chunk with AES-GCM */
  async decryptChunk(method, key, chunkHex) {
    if (method === 9 /* StringV1 */ || method === 8 /* FileV1 */) {
      const data = this.hexToBytes(chunkHex);
      const nonce = data.slice(0, NONCE_BYTES);
      const ctWithTag = data.slice(NONCE_BYTES);
      const plain = await crypto.subtle.decrypt(
        { name: "AES-GCM", iv: this.buf(nonce), tagLength: GCM_TAG_BITS },
        key,
        this.buf(ctWithTag)
      );
      return new TextDecoder().decode(plain);
    }
    if (method === 4 /* SJCL1a */) {
      console.warn("[joplin-sync] SJCL encryption method not supported, skipping chunk");
      return "";
    }
    throw new Error("Unsupported encryption method: " + method);
  }
  // === Helpers ===
  hexToBytes(hex) {
    if (!hex)
      return new Uint8Array(0);
    const bytes = new Uint8Array(hex.length / 2);
    for (let i = 0; i < bytes.length; i++) {
      bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    }
    return bytes;
  }
  bytesToHex(bytes) {
    return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  }
  buf(u8) {
    return new Uint8Array(u8.buffer, u8.byteOffset, u8.byteLength);
  }
  concat(a, b) {
    const out = new Uint8Array(a.length + b.length);
    out.set(a);
    out.set(b);
    return out;
  }
  base64ToBytes(b64) {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++)
      bytes[i] = bin.charCodeAt(i);
    return bytes;
  }
  /** Encrypt a serialized item string → encryption_cipher_text (method=StringV1) */
  async encryptItem(serialized, masterKeyId) {
    const key = this.loadedKeys.get(masterKeyId);
    if (!key)
      throw new Error("Master key not loaded: " + masterKeyId);
    const chunks = [];
    const CHUNK_SIZE = 5e3;
    for (let i = 0; i < serialized.length; i += CHUNK_SIZE) {
      const chunk2 = serialized.slice(i, i + CHUNK_SIZE);
      const encrypted = await this.encryptChunk(key, chunk2);
      chunks.push(encrypted);
    }
    return this.buildHeader(9 /* StringV1 */, masterKeyId, chunks);
  }
  /** Encrypt a plaintext chunk → hex-encoded nonce+ciphertext+tag */
  async encryptChunk(key, plain) {
    const nonce = crypto.getRandomValues(new Uint8Array(NONCE_BYTES));
    const encoded = new TextEncoder().encode(plain);
    const encrypted = await crypto.subtle.encrypt(
      { name: "AES-GCM", iv: this.buf(nonce), tagLength: GCM_TAG_BITS },
      key,
      this.buf(encoded)
    );
    const encryptedBytes = new Uint8Array(encrypted);
    const combined = this.concat(nonce, encryptedBytes);
    return this.bytesToHex(combined);
  }
  /** Build Joplin header hex: [3B len][1B ver][2B method][32B masterKeyId] + chunks */
  buildHeader(method, masterKeyId, chunks) {
    const headerBytes = new Uint8Array(1 + 2 + 32);
    let p = 0;
    headerBytes[p++] = 1;
    headerBytes[p++] = method >> 8 & 255;
    headerBytes[p++] = method & 255;
    const mkBytes = this.hexToBytes(masterKeyId);
    headerBytes.set(mkBytes, p);
    p += 32;
    const headerHex = this.bytesToHex(headerBytes);
    const hLenHex = headerBytes.length.toString(16).padStart(6, "0");
    let out = hLenHex + headerHex;
    for (const chunk2 of chunks) {
      const chunkBytes = chunk2.length / 2;
      out += chunkBytes.toString(16).padStart(6, "0") + chunk2;
    }
    return out;
  }
  get hasLoadedKeys() {
    return this.loadedKeys.size > 0;
  }
  get availableMasterKeys() {
    return [...this.masterKeyItems.keys()];
  }
  get firstLoadedKeyId() {
    return this.loadedKeys.keys().next().value ?? null;
  }
};

// src/main.ts
var JoplinSyncPlugin = class extends import_obsidian10.Plugin {
  constructor() {
    super(...arguments);
    this.initialized = false;
  }
  async onload() {
    await this.loadSettings();
    this.api = new JoplinServerApi(() => ({
      baseUrl: this.settings.serverUrl,
      email: this.settings.email,
      password: this.settings.password
    }));
    this.mapping = new MappingStore(this);
    await this.mapping.load();
    this.statusBar = new StatusBar(this.addStatusBarItem());
    this.e2ee = new EncryptionService();
    this.engine = new SyncEngine(this);
    this.addSettingTab(new JoplinSyncSettingTab(this.app, this));
    this.addCommand({
      id: "joplin-upload-all",
      name: "Upload vault to Joplin Server",
      callback: () => this.engine.runFullUpload()
    });
    this.addCommand({
      id: "joplin-sync-now",
      name: "Sync now",
      callback: () => this.engine.syncCycle()
    });
    this.addCommand({
      id: "joplin-force-push",
      name: "Force push to server (overwrite remote)",
      callback: () => this.engine.forcePush()
    });
    this.addCommand({
      id: "joplin-force-pull",
      name: "Force pull from server (overwrite local)",
      callback: () => this.engine.forcePull()
    });
    this.addCommand({
      id: "joplin-test-connection",
      name: "Test Joplin Server connection",
      callback: async () => {
        try {
          await this.api.login();
          new import_obsidian10.Notice("Joplin Server: connection OK");
        } catch (e) {
          new import_obsidian10.Notice("Connection failed: " + e.message);
        }
      }
    });
    this.addCommand({
      id: "joplin-show-about",
      name: "About / Status",
      callback: () => {
        const total = this.mapping.all().length;
        new import_obsidian10.Notice("v0.2.1\nMapped items: " + total + "\nDelta cursor: " + (this.mapping.getDeltaCursor() ? "yes" : "no"));
      }
    });
    if (this.settings.serverUrl) {
      this.engine.startWatching();
      this.engine.startScheduler();
    }
  }
  onunload() {
    void this.engine?.shutdown();
    void this.mapping?.flush();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data ?? {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  logSync(type, ok, fail) {
    this.settings.syncLog.unshift({ time: Date.now(), type, ok, fail });
    if (this.settings.syncLog.length > 5)
      this.settings.syncLog.length = 5;
    void this.saveSettings();
  }
};
