/*
THIS IS A GENERATED BUNDLE FOR OBSIDIAN PLUGIN.
DO NOT EDIT THIS FILE DIRECTLY.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JoplinSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings/PluginSettings.ts
var DEFAULT_SETTINGS = {
  serverUrl: "",
  email: "",
  password: "",
  syncIntervalSec: 300,
  syncOnStartup: false,
  conflictStrategy: "duplicate",
  excludePatterns: [".obsidian/", "_conflicts/", "templates/"],
  attachmentFolder: "attachments",
  maxAttachmentMB: 100,
  clientId: "",
  logLevel: "info"
};

// src/settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var JoplinSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Joplin Server").setHeading();
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc("e.g. https://joplin.example.com (without /api)").addText((t) => t.setPlaceholder("https://joplin.example.com").setValue(this.plugin.settings.serverUrl).onChange(async (v) => {
      this.plugin.settings.serverUrl = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Email").addText((t) => t.setValue(this.plugin.settings.email).onChange(async (v) => {
      this.plugin.settings.email = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Password").setDesc("Warning: stored in plaintext in plugin data.json").addText((t) => {
      t.inputEl.type = "password";
      t.setValue(this.plugin.settings.password).onChange(async (v) => {
        this.plugin.settings.password = v;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Test connection").addButton((b) => b.setButtonText("Test connection").setCta().onClick(async () => {
      b.setDisabled(true).setButtonText("Testing\u2026");
      try {
        await this.plugin.api.login();
        new import_obsidian.Notice("\u2705 Connection OK");
      } catch (e) {
        new import_obsidian.Notice("\u274C Connection failed: " + e.message, 8e3);
      } finally {
        b.setDisabled(false).setButtonText("Test connection");
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Sync behavior").setHeading();
    new import_obsidian.Setting(containerEl).setName("Auto sync interval").setDesc("Seconds. 0 = manual only (min 60)").addText((t) => t.setValue(String(this.plugin.settings.syncIntervalSec)).onChange(async (v) => {
      const n = parseInt(v);
      if (!isNaN(n) && n >= 0) {
        this.plugin.settings.syncIntervalSec = n;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Sync on startup").addToggle((t) => t.setValue(this.plugin.settings.syncOnStartup).onChange(async (v) => {
      this.plugin.settings.syncOnStartup = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Conflict strategy").addDropdown((d) => d.addOption("duplicate", "Duplicate").addOption("local-wins", "Local wins").addOption("remote-wins", "Remote wins").setValue(this.plugin.settings.conflictStrategy).onChange(async (v) => {
      this.plugin.settings.conflictStrategy = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Scope").setHeading();
    new import_obsidian.Setting(containerEl).setName("Exclude patterns").setDesc("Comma-separated path prefixes to exclude").addText((t) => t.setValue(this.plugin.settings.excludePatterns.join(", ")).onChange(async (v) => {
      this.plugin.settings.excludePatterns = v.split(",").map((s) => s.trim()).filter(Boolean);
      await this.plugin.saveSettings();
    }));
  }
};

// src/api/JoplinServerApi.ts
var import_obsidian2 = require("obsidian");
var JoplinServerApi = class {
  constructor(getConfig) {
    this.sessionId = null;
    this.getConfig = getConfig;
  }
  async login() {
    const { baseUrl, email, password } = this.getConfig();
    const res = await (0, import_obsidian2.requestUrl)({
      url: this.trimSlash(baseUrl) + "/api/sessions",
      method: "POST",
      contentType: "application/json",
      body: JSON.stringify({ email, password }),
      throw: false
    });
    if (res.status !== 200)
      throw new Error("Login failed (" + res.status + "): " + res.text);
    this.sessionId = res.json.id;
  }
  async exec(method, path, opts = {}) {
    if (!this.sessionId)
      await this.login();
    const maxRetries = opts.retries ?? 3;
    for (let attempt = 0; ; attempt++) {
      const param = {
        url: this.trimSlash(this.getConfig().baseUrl) + path,
        method,
        headers: {
          "X-API-AUTH": this.sessionId,
          "X-API-MIN-VERSION": "2.6.0"
        },
        body: opts.body,
        throw: false
      };
      if (opts.contentType)
        param.headers["Content-Type"] = opts.contentType;
      const res = await (0, import_obsidian2.requestUrl)(param);
      if (res.status === 401 && attempt === 0) {
        await this.login();
        continue;
      }
      if (res.status >= 500 && attempt < maxRetries) {
        await this.sleep(Math.pow(4, attempt) * 1e3);
        continue;
      }
      return res;
    }
  }
  itemPath(name, suffix = "") {
    return "/api/items/root:/" + encodeURIComponent(name) + ":" + suffix;
  }
  async getItem(name) {
    const res = await this.exec("GET", this.itemPath(name, "/content"));
    if (res.status === 404)
      return null;
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.text;
  }
  async putItem(name, content) {
    const res = await this.exec("PUT", this.itemPath(name, "/content"), {
      body: content,
      contentType: "application/octet-stream"
    });
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.json;
  }
  async deleteItem(name) {
    const res = await this.exec("DELETE", this.itemPath(name));
    if (res.status !== 200 && res.status !== 404)
      throw new ApiError(res.status, res.text);
  }
  async listChildren(cursor) {
    const q = cursor ? "?cursor=" + encodeURIComponent(cursor) : "";
    const res = await this.exec("GET", "/api/items/root:/:/children" + q);
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.json;
  }
  async delta(cursor) {
    const q = cursor ? "?cursor=" + encodeURIComponent(cursor) : "";
    const res = await this.exec("GET", "/api/items/root:/:/delta" + q);
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.json;
  }
  async acquireLock(type, clientType, clientId) {
    const res = await this.exec("POST", "/api/locks", {
      body: JSON.stringify({ type, clientType, clientId }),
      contentType: "application/json"
    });
    if (res.status === 409)
      throw new LockConflictError(res.text);
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.json;
  }
  async releaseLock(type, clientType, clientId) {
    await this.exec("DELETE", "/api/locks/" + type + "_" + clientType + "_" + clientId);
  }
  async listLocks() {
    const res = await this.exec("GET", "/api/locks");
    if (res.status !== 200)
      throw new ApiError(res.status, res.text);
    return res.json;
  }
  trimSlash(u) {
    return u.replace(/\/+$/, "");
  }
  sleep(ms) {
    return new Promise((r) => setTimeout(r, ms));
  }
};
var ApiError = class extends Error {
  constructor(status, text) {
    super("API error " + status + ": " + text);
    this.status = status;
  }
};
var LockConflictError = class extends Error {
};

// src/mapping/MappingStore.ts
var MappingStore = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.data = { version: 1, deltaCursor: "", entries: [], tombstones: [] };
    this.byId = /* @__PURE__ */ new Map();
    this.byPath = /* @__PURE__ */ new Map();
    this.dirty = false;
  }
  get filePath() {
    return this.plugin.manifest.dir + "/data/mapping.json";
  }
  async load() {
    const adapter = this.plugin.app.vault.adapter;
    if (adapter.exists) {
      if (await adapter.exists(this.filePath)) {
        this.data = JSON.parse(await adapter.read(this.filePath));
      }
    }
    this.rebuildIndexes();
  }
  async flush() {
    if (!this.dirty)
      return;
    const adapter = this.plugin.app.vault.adapter;
    const dir = this.plugin.manifest.dir + "/data";
    if (!await adapter.exists(dir))
      await adapter.mkdir(dir);
    const tmp = this.filePath + ".tmp";
    await adapter.write(tmp, JSON.stringify(this.data));
    if (await adapter.exists(this.filePath))
      await adapter.remove(this.filePath);
    await adapter.rename(tmp, this.filePath);
    this.dirty = false;
  }
  getByPath(path) {
    return this.byPath.get(path);
  }
  getById(id) {
    return this.byId.get(id);
  }
  all() {
    return this.data.entries;
  }
  getDeltaCursor() {
    return this.data.deltaCursor;
  }
  setDeltaCursor(cursor) {
    this.data.deltaCursor = cursor;
    this.dirty = true;
  }
  upsert(entry) {
    const existing = this.byId.get(entry.joplinId);
    if (existing) {
      this.byPath.delete(existing.path);
      Object.assign(existing, entry);
      this.byPath.set(existing.path, existing);
    } else {
      this.data.entries.push(entry);
      this.byId.set(entry.joplinId, entry);
      this.byPath.set(entry.path, entry);
    }
    this.dirty = true;
  }
  remove(joplinId) {
    const e = this.byId.get(joplinId);
    if (!e)
      return;
    this.data.entries = this.data.entries.filter((x) => x.joplinId !== joplinId);
    this.byId.delete(joplinId);
    this.byPath.delete(e.path);
    this.dirty = true;
  }
  get tombstones() {
    return this.data.tombstones;
  }
  addTombstone(joplinId, type) {
    this.data.tombstones.push({ joplinId, type, deletedAt: Date.now() });
    this.dirty = true;
  }
  clearTombstone(joplinId) {
    this.data.tombstones = this.data.tombstones.filter((t) => t.joplinId !== joplinId);
    this.dirty = true;
  }
  renamePrefix(oldPrefix, newPrefix) {
    for (const e of this.data.entries) {
      if (e.path === oldPrefix || e.path.startsWith(oldPrefix)) {
        this.byPath.delete(e.path);
        e.path = newPrefix + e.path.slice(oldPrefix.length);
        this.byPath.set(e.path, e);
      }
    }
    this.dirty = true;
  }
  rebuildIndexes() {
    this.byId.clear();
    this.byPath.clear();
    for (const e of this.data.entries) {
      this.byId.set(e.joplinId, e);
      this.byPath.set(e.path, e);
    }
  }
};

// src/core/SyncEngine.ts
var import_obsidian3 = require("obsidian");

// src/convert/JoplinSerializer.ts
var NOTE_FIELD_ORDER = [
  "id",
  "parent_id",
  "created_time",
  "updated_time",
  "is_conflict",
  "latitude",
  "longitude",
  "altitude",
  "author",
  "source_url",
  "is_todo",
  "todo_due",
  "todo_completed",
  "source",
  "source_application",
  "application_data",
  "order",
  "user_created_time",
  "user_updated_time",
  "encryption_cipher_text",
  "encryption_applied",
  "markup_language",
  "is_shared",
  "share_id",
  "conflict_original_id",
  "master_key_id",
  "user_data",
  "deleted_time",
  "type_"
];
var FOLDER_FIELD_ORDER = [
  "id",
  "created_time",
  "updated_time",
  "user_created_time",
  "user_updated_time",
  "encryption_cipher_text",
  "encryption_applied",
  "parent_id",
  "is_shared",
  "share_id",
  "master_key_id",
  "icon",
  "user_data",
  "deleted_time",
  "type_"
];
var RESOURCE_FIELD_ORDER = [
  "id",
  "mime",
  "filename",
  "created_time",
  "updated_time",
  "user_created_time",
  "user_updated_time",
  "file_extension",
  "encryption_cipher_text",
  "encryption_applied",
  "encryption_blob_encrypted",
  "size",
  "is_shared",
  "share_id",
  "master_key_id",
  "user_data",
  "blob_updated_time",
  "ocr_text",
  "ocr_details",
  "ocr_status",
  "ocr_error",
  "type_"
];
var TIME_FIELDS = /* @__PURE__ */ new Set([
  "created_time",
  "updated_time",
  "user_created_time",
  "user_updated_time"
]);
var DEFAULTS = {
  is_conflict: 0,
  latitude: "0.00000000",
  longitude: "0.00000000",
  altitude: "0.0000",
  author: "",
  source_url: "",
  is_todo: 0,
  todo_due: 0,
  todo_completed: 0,
  source: "obsidian-joplin-sync",
  source_application: "net.obsidian.joplin-server-sync",
  application_data: "",
  order: 0,
  encryption_cipher_text: "",
  encryption_applied: 0,
  markup_language: 1,
  is_shared: 0,
  share_id: "",
  conflict_original_id: "",
  master_key_id: "",
  user_data: "",
  deleted_time: 0,
  icon: ""
};
var JoplinSerializer = class {
  serialize(item) {
    const order = this.fieldOrder(item.type_);
    const lines = [];
    lines.push(item.title ?? "");
    lines.push("");
    if (item.type_ === 1 /* Note */) {
      lines.push(item.body ?? "");
      lines.push("");
    }
    for (const key of order) {
      let value = item[key] ?? DEFAULTS[key] ?? "";
      if (TIME_FIELDS.has(key))
        value = this.formatTime(value);
      lines.push(key + ": " + value);
    }
    return lines.join("\n");
  }
  unserialize(raw) {
    const lines = raw.split("\n");
    const item = {};
    let bodyEndIndex = lines.length;
    for (let i = lines.length - 1; i >= 0; i--) {
      const line = lines[i];
      if (line.trim() === "") {
        bodyEndIndex = i;
        break;
      }
      const sep = line.indexOf(":");
      if (sep < 0)
        throw new Error("Invalid metadata line: " + line);
      const key = line.slice(0, sep).trim();
      const value = line.slice(sep + 1).trim();
      item[key] = TIME_FIELDS.has(key) ? this.parseTime(value) : this.coerce(key, value);
    }
    const headerBody = lines.slice(0, bodyEndIndex);
    item.title = headerBody[0] ?? "";
    if (Number(item.type_) === 1 /* Note */) {
      item.body = headerBody.slice(2).join("\n");
    }
    item.type_ = Number(item.type_);
    return item;
  }
  fieldOrder(type) {
    switch (type) {
      case 1 /* Note */:
        return NOTE_FIELD_ORDER;
      case 2 /* Folder */:
        return FOLDER_FIELD_ORDER;
      case 4 /* Resource */:
        return RESOURCE_FIELD_ORDER;
      default:
        return NOTE_FIELD_ORDER;
    }
  }
  formatTime(ms) {
    return new Date(ms || 0).toISOString();
  }
  parseTime(s) {
    return s ? new Date(s).getTime() : 0;
  }
  coerce(key, value) {
    const numeric = /* @__PURE__ */ new Set([
      "type_",
      "is_conflict",
      "is_todo",
      "todo_due",
      "todo_completed",
      "encryption_applied",
      "markup_language",
      "is_shared",
      "order",
      "size",
      "deleted_time",
      "blob_updated_time"
    ]);
    return numeric.has(key) ? Number(value) : value;
  }
};

// src/core/SyncInfo.ts
var SUPPORTED_SYNC_VERSION = 3;
var SyncInfoHandler = class {
  constructor(api) {
    this.api = api;
  }
  async checkOrInit() {
    const raw = await this.api.getItem("info.json");
    if (raw === null) {
      const info2 = { version: SUPPORTED_SYNC_VERSION };
      await this.api.putItem("info.json", JSON.stringify(info2));
      return info2;
    }
    const info = JSON.parse(raw);
    if (info.version > SUPPORTED_SYNC_VERSION) {
      throw new Error("Sync target version " + info.version + " > supported " + SUPPORTED_SYNC_VERSION + ". Please update the plugin.");
    }
    if (info.version < SUPPORTED_SYNC_VERSION) {
      throw new Error("Sync target needs upgrade (v" + info.version + "). Run sync in official Joplin client first.");
    }
    if (info.e2ee?.value === true) {
      throw new Error("This sync target has E2EE enabled, which is not yet supported.");
    }
    return info;
  }
};

// src/mapping/IdGenerator.ts
function createJoplinId() {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

// src/core/SyncEngine.ts
var SyncEngine = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.serializer = new JoplinSerializer();
    this.running = false;
    this.state = 0 /* Idle */;
    this.syncInfo = new SyncInfoHandler(plugin.api);
  }
  async runFullUpload() {
    if (this.running) {
      new import_obsidian3.Notice("Sync already in progress");
      return;
    }
    this.running = true;
    try {
      await this.plugin.api.login();
      await this.syncInfo.checkOrInit();
      const rootFolderId = await this.ensureRootFolder();
      const files = this.collectMarkdownFiles();
      let done = 0, skipped = 0;
      const failed = [];
      for (const batch of chunk(files, 5)) {
        await Promise.all(batch.map(async (file) => {
          try {
            const changed = await this.uploadNote(file, rootFolderId);
            changed ? done++ : skipped++;
          } catch (e) {
            failed.push(file.path + ": " + e.message);
          }
          this.plugin.statusBar.setProgress(done + skipped, files.length);
        }));
        await this.plugin.mapping.flush();
      }
      new import_obsidian3.Notice("Upload done: " + done + " uploaded, " + skipped + " unchanged, " + failed.length + " failed");
      if (failed.length)
        console.error("[joplin-sync] failures:", failed);
    } finally {
      this.running = false;
      await this.plugin.mapping.flush();
      this.plugin.statusBar.setIdle();
    }
  }
  async uploadNote(file, parentId) {
    const content = await this.plugin.app.vault.read(file);
    const hash = await sha256(content);
    const existing = this.plugin.mapping.getByPath(file.path);
    if (existing && existing.localHash === hash)
      return false;
    const id = existing?.joplinId ?? createJoplinId();
    const item = {
      id,
      parent_id: parentId,
      title: file.basename,
      body: content,
      created_time: file.stat.ctime,
      updated_time: file.stat.mtime,
      user_created_time: file.stat.ctime,
      user_updated_time: file.stat.mtime,
      type_: 1 /* Note */,
      encryption_applied: 0,
      encryption_cipher_text: "",
      markup_language: 1
    };
    const result = await this.plugin.api.putItem(id + ".md", this.serializer.serialize(item));
    this.plugin.mapping.upsert({
      joplinId: id,
      path: file.path,
      type: 1 /* Note */,
      localHash: hash,
      remoteUpdatedTime: result.updated_time,
      syncedAt: Date.now()
    });
    return true;
  }
  async ensureRootFolder() {
    const ROOT_KEY = "__root__/";
    const existing = this.plugin.mapping.getByPath(ROOT_KEY);
    if (existing)
      return existing.joplinId;
    const id = createJoplinId();
    const item = {
      id,
      parent_id: "",
      title: "Obsidian",
      created_time: Date.now(),
      updated_time: Date.now(),
      user_created_time: Date.now(),
      user_updated_time: Date.now(),
      type_: 2 /* Folder */,
      encryption_applied: 0,
      encryption_cipher_text: ""
    };
    const res = await this.plugin.api.putItem(id + ".md", this.serializer.serialize(item));
    this.plugin.mapping.upsert({
      joplinId: id,
      path: ROOT_KEY,
      type: 2 /* Folder */,
      localHash: "",
      remoteUpdatedTime: res.updated_time,
      syncedAt: Date.now()
    });
    return id;
  }
  collectMarkdownFiles() {
    const excludes = this.plugin.settings.excludePatterns;
    return this.plugin.app.vault.getMarkdownFiles().filter((f) => !excludes.some((p) => f.path.startsWith(p)));
  }
  startWatching() {
  }
  startScheduler() {
  }
  async shutdown() {
  }
};
async function sha256(text) {
  const data = typeof text === "string" ? new TextEncoder().encode(text) : text;
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0")).join("");
}
function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size)
    out.push(arr.slice(i, i + size));
  return out;
}

// src/ui/StatusBar.ts
var StatusBar = class {
  constructor(el) {
    this.el = el;
    this.el.addClass("joplin-sync-status");
    this.setIdle();
  }
  setIdle() {
    this.el.setText("Joplin: idle");
    this.el.className = "joplin-sync-status";
  }
  setSyncing() {
    this.el.setText("Joplin: syncing\u2026");
    this.el.className = "joplin-sync-status syncing";
  }
  setOk(time) {
    const t = new Date(time).toLocaleTimeString();
    this.el.setText("Joplin: OK (" + t + ")");
    this.el.className = "joplin-sync-status ok";
  }
  setError(msg) {
    this.el.setText("Joplin: error");
    this.el.className = "joplin-sync-status error";
    console.error("[joplin-sync]", msg);
  }
  setProgress(done, total) {
    this.el.setText("Joplin: " + done + "/" + total);
  }
};

// src/main.ts
var JoplinSyncPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.api = new JoplinServerApi(() => ({
      baseUrl: this.settings.serverUrl,
      email: this.settings.email,
      password: this.settings.password
    }));
    this.mapping = new MappingStore(this);
    await this.mapping.load();
    this.statusBar = new StatusBar(this.addStatusBarItem());
    this.engine = new SyncEngine(this);
    this.addSettingTab(new JoplinSyncSettingTab(this.app, this));
    this.addCommand({
      id: "joplin-upload-all",
      name: "Upload vault to Joplin Server",
      callback: () => this.engine.runFullUpload()
    });
    this.addCommand({
      id: "joplin-test-connection",
      name: "Test Joplin Server connection",
      callback: async () => {
        try {
          await this.api.login();
          new import_obsidian4.Notice("Joplin Server: connection OK");
        } catch (e) {
          new import_obsidian4.Notice("Connection failed: " + e.message);
        }
      }
    });
    this.addCommand({
      id: "joplin-show-about",
      name: "Joplin Server Sync: About / Status",
      callback: () => {
        const total = this.mapping.all().length;
        new import_obsidian4.Notice("Joplin Server Sync v0.1.0\nMapped items: " + total + "\nDelta cursor: " + (this.mapping.getDeltaCursor() ? "yes" : "no"));
      }
    });
  }
  async onunload() {
    await this.engine?.shutdown();
    await this.mapping?.flush();
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
